// Code generated by ent, DO NOT EDIT.

package season

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
)

const (
	// Label holds the string label denoting the season type in the database.
	Label = "season"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldIsCurrent holds the string denoting the is_current field in the database.
	FieldIsCurrent = "is_current"
	// EdgeTournaments holds the string denoting the tournaments edge name in mutations.
	EdgeTournaments = "tournaments"
	// EdgeLeagues holds the string denoting the leagues edge name in mutations.
	EdgeLeagues = "leagues"
	// EdgePicks holds the string denoting the picks edge name in mutations.
	EdgePicks = "picks"
	// EdgeGolferSeasons holds the string denoting the golfer_seasons edge name in mutations.
	EdgeGolferSeasons = "golfer_seasons"
	// Table holds the table name of the season in the database.
	Table = "seasons"
	// TournamentsTable is the table that holds the tournaments relation/edge.
	TournamentsTable = "tournaments"
	// TournamentsInverseTable is the table name for the Tournament entity.
	// It exists in this package in order to avoid circular dependency with the "tournament" package.
	TournamentsInverseTable = "tournaments"
	// TournamentsColumn is the table column denoting the tournaments relation/edge.
	TournamentsColumn = "season_tournaments"
	// LeaguesTable is the table that holds the leagues relation/edge.
	LeaguesTable = "leagues"
	// LeaguesInverseTable is the table name for the League entity.
	// It exists in this package in order to avoid circular dependency with the "league" package.
	LeaguesInverseTable = "leagues"
	// LeaguesColumn is the table column denoting the leagues relation/edge.
	LeaguesColumn = "season_leagues"
	// PicksTable is the table that holds the picks relation/edge.
	PicksTable = "picks"
	// PicksInverseTable is the table name for the Pick entity.
	// It exists in this package in order to avoid circular dependency with the "pick" package.
	PicksInverseTable = "picks"
	// PicksColumn is the table column denoting the picks relation/edge.
	PicksColumn = "season_picks"
	// GolferSeasonsTable is the table that holds the golfer_seasons relation/edge.
	GolferSeasonsTable = "golfer_seasons"
	// GolferSeasonsInverseTable is the table name for the GolferSeason entity.
	// It exists in this package in order to avoid circular dependency with the "golferseason" package.
	GolferSeasonsInverseTable = "golfer_seasons"
	// GolferSeasonsColumn is the table column denoting the golfer_seasons relation/edge.
	GolferSeasonsColumn = "season_golfer_seasons"
)

// Columns holds all SQL columns for season fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldYear,
	FieldStartDate,
	FieldEndDate,
	FieldIsCurrent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// YearValidator is a validator for the "year" field. It is called by the builders before save.
	YearValidator func(int) error
	// DefaultIsCurrent holds the default value on creation for the "is_current" field.
	DefaultIsCurrent bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Season queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByIsCurrent orders the results by the is_current field.
func ByIsCurrent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCurrent, opts...).ToFunc()
}

// ByTournamentsCount orders the results by tournaments count.
func ByTournamentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTournamentsStep(), opts...)
	}
}

// ByTournaments orders the results by tournaments terms.
func ByTournaments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTournamentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLeaguesCount orders the results by leagues count.
func ByLeaguesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLeaguesStep(), opts...)
	}
}

// ByLeagues orders the results by leagues terms.
func ByLeagues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLeaguesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPicksCount orders the results by picks count.
func ByPicksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPicksStep(), opts...)
	}
}

// ByPicks orders the results by picks terms.
func ByPicks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPicksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGolferSeasonsCount orders the results by golfer_seasons count.
func ByGolferSeasonsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGolferSeasonsStep(), opts...)
	}
}

// ByGolferSeasons orders the results by golfer_seasons terms.
func ByGolferSeasons(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGolferSeasonsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTournamentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TournamentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TournamentsTable, TournamentsColumn),
	)
}
func newLeaguesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LeaguesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LeaguesTable, LeaguesColumn),
	)
}
func newPicksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PicksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PicksTable, PicksColumn),
	)
}
func newGolferSeasonsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GolferSeasonsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GolferSeasonsTable, GolferSeasonsColumn),
	)
}
