// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rj-davidson/greenrats/ent/commissioneraction"
	"github.com/rj-davidson/greenrats/ent/emailreminder"
	"github.com/rj-davidson/greenrats/ent/golfer"
	"github.com/rj-davidson/greenrats/ent/league"
	"github.com/rj-davidson/greenrats/ent/leaguemembership"
	"github.com/rj-davidson/greenrats/ent/pick"
	"github.com/rj-davidson/greenrats/ent/syncstatus"
	"github.com/rj-davidson/greenrats/ent/tournament"
	"github.com/rj-davidson/greenrats/ent/tournamententry"
	"github.com/rj-davidson/greenrats/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CommissionerAction is the client for interacting with the CommissionerAction builders.
	CommissionerAction *CommissionerActionClient
	// EmailReminder is the client for interacting with the EmailReminder builders.
	EmailReminder *EmailReminderClient
	// Golfer is the client for interacting with the Golfer builders.
	Golfer *GolferClient
	// League is the client for interacting with the League builders.
	League *LeagueClient
	// LeagueMembership is the client for interacting with the LeagueMembership builders.
	LeagueMembership *LeagueMembershipClient
	// Pick is the client for interacting with the Pick builders.
	Pick *PickClient
	// SyncStatus is the client for interacting with the SyncStatus builders.
	SyncStatus *SyncStatusClient
	// Tournament is the client for interacting with the Tournament builders.
	Tournament *TournamentClient
	// TournamentEntry is the client for interacting with the TournamentEntry builders.
	TournamentEntry *TournamentEntryClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CommissionerAction = NewCommissionerActionClient(c.config)
	c.EmailReminder = NewEmailReminderClient(c.config)
	c.Golfer = NewGolferClient(c.config)
	c.League = NewLeagueClient(c.config)
	c.LeagueMembership = NewLeagueMembershipClient(c.config)
	c.Pick = NewPickClient(c.config)
	c.SyncStatus = NewSyncStatusClient(c.config)
	c.Tournament = NewTournamentClient(c.config)
	c.TournamentEntry = NewTournamentEntryClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		CommissionerAction: NewCommissionerActionClient(cfg),
		EmailReminder:      NewEmailReminderClient(cfg),
		Golfer:             NewGolferClient(cfg),
		League:             NewLeagueClient(cfg),
		LeagueMembership:   NewLeagueMembershipClient(cfg),
		Pick:               NewPickClient(cfg),
		SyncStatus:         NewSyncStatusClient(cfg),
		Tournament:         NewTournamentClient(cfg),
		TournamentEntry:    NewTournamentEntryClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		CommissionerAction: NewCommissionerActionClient(cfg),
		EmailReminder:      NewEmailReminderClient(cfg),
		Golfer:             NewGolferClient(cfg),
		League:             NewLeagueClient(cfg),
		LeagueMembership:   NewLeagueMembershipClient(cfg),
		Pick:               NewPickClient(cfg),
		SyncStatus:         NewSyncStatusClient(cfg),
		Tournament:         NewTournamentClient(cfg),
		TournamentEntry:    NewTournamentEntryClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CommissionerAction.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CommissionerAction, c.EmailReminder, c.Golfer, c.League, c.LeagueMembership,
		c.Pick, c.SyncStatus, c.Tournament, c.TournamentEntry, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CommissionerAction, c.EmailReminder, c.Golfer, c.League, c.LeagueMembership,
		c.Pick, c.SyncStatus, c.Tournament, c.TournamentEntry, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CommissionerActionMutation:
		return c.CommissionerAction.mutate(ctx, m)
	case *EmailReminderMutation:
		return c.EmailReminder.mutate(ctx, m)
	case *GolferMutation:
		return c.Golfer.mutate(ctx, m)
	case *LeagueMutation:
		return c.League.mutate(ctx, m)
	case *LeagueMembershipMutation:
		return c.LeagueMembership.mutate(ctx, m)
	case *PickMutation:
		return c.Pick.mutate(ctx, m)
	case *SyncStatusMutation:
		return c.SyncStatus.mutate(ctx, m)
	case *TournamentMutation:
		return c.Tournament.mutate(ctx, m)
	case *TournamentEntryMutation:
		return c.TournamentEntry.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CommissionerActionClient is a client for the CommissionerAction schema.
type CommissionerActionClient struct {
	config
}

// NewCommissionerActionClient returns a client for the CommissionerAction from the given config.
func NewCommissionerActionClient(c config) *CommissionerActionClient {
	return &CommissionerActionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `commissioneraction.Hooks(f(g(h())))`.
func (c *CommissionerActionClient) Use(hooks ...Hook) {
	c.hooks.CommissionerAction = append(c.hooks.CommissionerAction, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `commissioneraction.Intercept(f(g(h())))`.
func (c *CommissionerActionClient) Intercept(interceptors ...Interceptor) {
	c.inters.CommissionerAction = append(c.inters.CommissionerAction, interceptors...)
}

// Create returns a builder for creating a CommissionerAction entity.
func (c *CommissionerActionClient) Create() *CommissionerActionCreate {
	mutation := newCommissionerActionMutation(c.config, OpCreate)
	return &CommissionerActionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CommissionerAction entities.
func (c *CommissionerActionClient) CreateBulk(builders ...*CommissionerActionCreate) *CommissionerActionCreateBulk {
	return &CommissionerActionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CommissionerActionClient) MapCreateBulk(slice any, setFunc func(*CommissionerActionCreate, int)) *CommissionerActionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CommissionerActionCreateBulk{err: fmt.Errorf("calling to CommissionerActionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CommissionerActionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CommissionerActionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CommissionerAction.
func (c *CommissionerActionClient) Update() *CommissionerActionUpdate {
	mutation := newCommissionerActionMutation(c.config, OpUpdate)
	return &CommissionerActionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CommissionerActionClient) UpdateOne(_m *CommissionerAction) *CommissionerActionUpdateOne {
	mutation := newCommissionerActionMutation(c.config, OpUpdateOne, withCommissionerAction(_m))
	return &CommissionerActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CommissionerActionClient) UpdateOneID(id uuid.UUID) *CommissionerActionUpdateOne {
	mutation := newCommissionerActionMutation(c.config, OpUpdateOne, withCommissionerActionID(id))
	return &CommissionerActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CommissionerAction.
func (c *CommissionerActionClient) Delete() *CommissionerActionDelete {
	mutation := newCommissionerActionMutation(c.config, OpDelete)
	return &CommissionerActionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CommissionerActionClient) DeleteOne(_m *CommissionerAction) *CommissionerActionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CommissionerActionClient) DeleteOneID(id uuid.UUID) *CommissionerActionDeleteOne {
	builder := c.Delete().Where(commissioneraction.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CommissionerActionDeleteOne{builder}
}

// Query returns a query builder for CommissionerAction.
func (c *CommissionerActionClient) Query() *CommissionerActionQuery {
	return &CommissionerActionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCommissionerAction},
		inters: c.Interceptors(),
	}
}

// Get returns a CommissionerAction entity by its id.
func (c *CommissionerActionClient) Get(ctx context.Context, id uuid.UUID) (*CommissionerAction, error) {
	return c.Query().Where(commissioneraction.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CommissionerActionClient) GetX(ctx context.Context, id uuid.UUID) *CommissionerAction {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLeague queries the league edge of a CommissionerAction.
func (c *CommissionerActionClient) QueryLeague(_m *CommissionerAction) *LeagueQuery {
	query := (&LeagueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(commissioneraction.Table, commissioneraction.FieldID, id),
			sqlgraph.To(league.Table, league.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissioneraction.LeagueTable, commissioneraction.LeagueColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCommissioner queries the commissioner edge of a CommissionerAction.
func (c *CommissionerActionClient) QueryCommissioner(_m *CommissionerAction) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(commissioneraction.Table, commissioneraction.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissioneraction.CommissionerTable, commissioneraction.CommissionerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAffectedUser queries the affected_user edge of a CommissionerAction.
func (c *CommissionerActionClient) QueryAffectedUser(_m *CommissionerAction) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(commissioneraction.Table, commissioneraction.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissioneraction.AffectedUserTable, commissioneraction.AffectedUserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CommissionerActionClient) Hooks() []Hook {
	return c.hooks.CommissionerAction
}

// Interceptors returns the client interceptors.
func (c *CommissionerActionClient) Interceptors() []Interceptor {
	return c.inters.CommissionerAction
}

func (c *CommissionerActionClient) mutate(ctx context.Context, m *CommissionerActionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CommissionerActionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CommissionerActionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CommissionerActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CommissionerActionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CommissionerAction mutation op: %q", m.Op())
	}
}

// EmailReminderClient is a client for the EmailReminder schema.
type EmailReminderClient struct {
	config
}

// NewEmailReminderClient returns a client for the EmailReminder from the given config.
func NewEmailReminderClient(c config) *EmailReminderClient {
	return &EmailReminderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `emailreminder.Hooks(f(g(h())))`.
func (c *EmailReminderClient) Use(hooks ...Hook) {
	c.hooks.EmailReminder = append(c.hooks.EmailReminder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `emailreminder.Intercept(f(g(h())))`.
func (c *EmailReminderClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmailReminder = append(c.inters.EmailReminder, interceptors...)
}

// Create returns a builder for creating a EmailReminder entity.
func (c *EmailReminderClient) Create() *EmailReminderCreate {
	mutation := newEmailReminderMutation(c.config, OpCreate)
	return &EmailReminderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmailReminder entities.
func (c *EmailReminderClient) CreateBulk(builders ...*EmailReminderCreate) *EmailReminderCreateBulk {
	return &EmailReminderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmailReminderClient) MapCreateBulk(slice any, setFunc func(*EmailReminderCreate, int)) *EmailReminderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmailReminderCreateBulk{err: fmt.Errorf("calling to EmailReminderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmailReminderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmailReminderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmailReminder.
func (c *EmailReminderClient) Update() *EmailReminderUpdate {
	mutation := newEmailReminderMutation(c.config, OpUpdate)
	return &EmailReminderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmailReminderClient) UpdateOne(_m *EmailReminder) *EmailReminderUpdateOne {
	mutation := newEmailReminderMutation(c.config, OpUpdateOne, withEmailReminder(_m))
	return &EmailReminderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmailReminderClient) UpdateOneID(id uuid.UUID) *EmailReminderUpdateOne {
	mutation := newEmailReminderMutation(c.config, OpUpdateOne, withEmailReminderID(id))
	return &EmailReminderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmailReminder.
func (c *EmailReminderClient) Delete() *EmailReminderDelete {
	mutation := newEmailReminderMutation(c.config, OpDelete)
	return &EmailReminderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmailReminderClient) DeleteOne(_m *EmailReminder) *EmailReminderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmailReminderClient) DeleteOneID(id uuid.UUID) *EmailReminderDeleteOne {
	builder := c.Delete().Where(emailreminder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmailReminderDeleteOne{builder}
}

// Query returns a query builder for EmailReminder.
func (c *EmailReminderClient) Query() *EmailReminderQuery {
	return &EmailReminderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmailReminder},
		inters: c.Interceptors(),
	}
}

// Get returns a EmailReminder entity by its id.
func (c *EmailReminderClient) Get(ctx context.Context, id uuid.UUID) (*EmailReminder, error) {
	return c.Query().Where(emailreminder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmailReminderClient) GetX(ctx context.Context, id uuid.UUID) *EmailReminder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a EmailReminder.
func (c *EmailReminderClient) QueryUser(_m *EmailReminder) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(emailreminder.Table, emailreminder.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, emailreminder.UserTable, emailreminder.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTournament queries the tournament edge of a EmailReminder.
func (c *EmailReminderClient) QueryTournament(_m *EmailReminder) *TournamentQuery {
	query := (&TournamentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(emailreminder.Table, emailreminder.FieldID, id),
			sqlgraph.To(tournament.Table, tournament.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, emailreminder.TournamentTable, emailreminder.TournamentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLeague queries the league edge of a EmailReminder.
func (c *EmailReminderClient) QueryLeague(_m *EmailReminder) *LeagueQuery {
	query := (&LeagueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(emailreminder.Table, emailreminder.FieldID, id),
			sqlgraph.To(league.Table, league.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, emailreminder.LeagueTable, emailreminder.LeagueColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EmailReminderClient) Hooks() []Hook {
	return c.hooks.EmailReminder
}

// Interceptors returns the client interceptors.
func (c *EmailReminderClient) Interceptors() []Interceptor {
	return c.inters.EmailReminder
}

func (c *EmailReminderClient) mutate(ctx context.Context, m *EmailReminderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmailReminderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmailReminderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmailReminderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmailReminderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmailReminder mutation op: %q", m.Op())
	}
}

// GolferClient is a client for the Golfer schema.
type GolferClient struct {
	config
}

// NewGolferClient returns a client for the Golfer from the given config.
func NewGolferClient(c config) *GolferClient {
	return &GolferClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `golfer.Hooks(f(g(h())))`.
func (c *GolferClient) Use(hooks ...Hook) {
	c.hooks.Golfer = append(c.hooks.Golfer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `golfer.Intercept(f(g(h())))`.
func (c *GolferClient) Intercept(interceptors ...Interceptor) {
	c.inters.Golfer = append(c.inters.Golfer, interceptors...)
}

// Create returns a builder for creating a Golfer entity.
func (c *GolferClient) Create() *GolferCreate {
	mutation := newGolferMutation(c.config, OpCreate)
	return &GolferCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Golfer entities.
func (c *GolferClient) CreateBulk(builders ...*GolferCreate) *GolferCreateBulk {
	return &GolferCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GolferClient) MapCreateBulk(slice any, setFunc func(*GolferCreate, int)) *GolferCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GolferCreateBulk{err: fmt.Errorf("calling to GolferClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GolferCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GolferCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Golfer.
func (c *GolferClient) Update() *GolferUpdate {
	mutation := newGolferMutation(c.config, OpUpdate)
	return &GolferUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GolferClient) UpdateOne(_m *Golfer) *GolferUpdateOne {
	mutation := newGolferMutation(c.config, OpUpdateOne, withGolfer(_m))
	return &GolferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GolferClient) UpdateOneID(id uuid.UUID) *GolferUpdateOne {
	mutation := newGolferMutation(c.config, OpUpdateOne, withGolferID(id))
	return &GolferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Golfer.
func (c *GolferClient) Delete() *GolferDelete {
	mutation := newGolferMutation(c.config, OpDelete)
	return &GolferDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GolferClient) DeleteOne(_m *Golfer) *GolferDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GolferClient) DeleteOneID(id uuid.UUID) *GolferDeleteOne {
	builder := c.Delete().Where(golfer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GolferDeleteOne{builder}
}

// Query returns a query builder for Golfer.
func (c *GolferClient) Query() *GolferQuery {
	return &GolferQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGolfer},
		inters: c.Interceptors(),
	}
}

// Get returns a Golfer entity by its id.
func (c *GolferClient) Get(ctx context.Context, id uuid.UUID) (*Golfer, error) {
	return c.Query().Where(golfer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GolferClient) GetX(ctx context.Context, id uuid.UUID) *Golfer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPicks queries the picks edge of a Golfer.
func (c *GolferClient) QueryPicks(_m *Golfer) *PickQuery {
	query := (&PickClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(golfer.Table, golfer.FieldID, id),
			sqlgraph.To(pick.Table, pick.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, golfer.PicksTable, golfer.PicksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEntries queries the entries edge of a Golfer.
func (c *GolferClient) QueryEntries(_m *Golfer) *TournamentEntryQuery {
	query := (&TournamentEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(golfer.Table, golfer.FieldID, id),
			sqlgraph.To(tournamententry.Table, tournamententry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, golfer.EntriesTable, golfer.EntriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GolferClient) Hooks() []Hook {
	return c.hooks.Golfer
}

// Interceptors returns the client interceptors.
func (c *GolferClient) Interceptors() []Interceptor {
	return c.inters.Golfer
}

func (c *GolferClient) mutate(ctx context.Context, m *GolferMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GolferCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GolferUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GolferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GolferDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Golfer mutation op: %q", m.Op())
	}
}

// LeagueClient is a client for the League schema.
type LeagueClient struct {
	config
}

// NewLeagueClient returns a client for the League from the given config.
func NewLeagueClient(c config) *LeagueClient {
	return &LeagueClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `league.Hooks(f(g(h())))`.
func (c *LeagueClient) Use(hooks ...Hook) {
	c.hooks.League = append(c.hooks.League, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `league.Intercept(f(g(h())))`.
func (c *LeagueClient) Intercept(interceptors ...Interceptor) {
	c.inters.League = append(c.inters.League, interceptors...)
}

// Create returns a builder for creating a League entity.
func (c *LeagueClient) Create() *LeagueCreate {
	mutation := newLeagueMutation(c.config, OpCreate)
	return &LeagueCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of League entities.
func (c *LeagueClient) CreateBulk(builders ...*LeagueCreate) *LeagueCreateBulk {
	return &LeagueCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LeagueClient) MapCreateBulk(slice any, setFunc func(*LeagueCreate, int)) *LeagueCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LeagueCreateBulk{err: fmt.Errorf("calling to LeagueClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LeagueCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LeagueCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for League.
func (c *LeagueClient) Update() *LeagueUpdate {
	mutation := newLeagueMutation(c.config, OpUpdate)
	return &LeagueUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LeagueClient) UpdateOne(_m *League) *LeagueUpdateOne {
	mutation := newLeagueMutation(c.config, OpUpdateOne, withLeague(_m))
	return &LeagueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LeagueClient) UpdateOneID(id uuid.UUID) *LeagueUpdateOne {
	mutation := newLeagueMutation(c.config, OpUpdateOne, withLeagueID(id))
	return &LeagueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for League.
func (c *LeagueClient) Delete() *LeagueDelete {
	mutation := newLeagueMutation(c.config, OpDelete)
	return &LeagueDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LeagueClient) DeleteOne(_m *League) *LeagueDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LeagueClient) DeleteOneID(id uuid.UUID) *LeagueDeleteOne {
	builder := c.Delete().Where(league.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LeagueDeleteOne{builder}
}

// Query returns a query builder for League.
func (c *LeagueClient) Query() *LeagueQuery {
	return &LeagueQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLeague},
		inters: c.Interceptors(),
	}
}

// Get returns a League entity by its id.
func (c *LeagueClient) Get(ctx context.Context, id uuid.UUID) (*League, error) {
	return c.Query().Where(league.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LeagueClient) GetX(ctx context.Context, id uuid.UUID) *League {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCreatedBy queries the created_by edge of a League.
func (c *LeagueClient) QueryCreatedBy(_m *League) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, league.CreatedByTable, league.CreatedByColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemberships queries the memberships edge of a League.
func (c *LeagueClient) QueryMemberships(_m *League) *LeagueMembershipQuery {
	query := (&LeagueMembershipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, id),
			sqlgraph.To(leaguemembership.Table, leaguemembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, league.MembershipsTable, league.MembershipsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPicks queries the picks edge of a League.
func (c *LeagueClient) QueryPicks(_m *League) *PickQuery {
	query := (&PickClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, id),
			sqlgraph.To(pick.Table, pick.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, league.PicksTable, league.PicksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCommissionerActions queries the commissioner_actions edge of a League.
func (c *LeagueClient) QueryCommissionerActions(_m *League) *CommissionerActionQuery {
	query := (&CommissionerActionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, id),
			sqlgraph.To(commissioneraction.Table, commissioneraction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, league.CommissionerActionsTable, league.CommissionerActionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEmailReminders queries the email_reminders edge of a League.
func (c *LeagueClient) QueryEmailReminders(_m *League) *EmailReminderQuery {
	query := (&EmailReminderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, id),
			sqlgraph.To(emailreminder.Table, emailreminder.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, league.EmailRemindersTable, league.EmailRemindersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LeagueClient) Hooks() []Hook {
	return c.hooks.League
}

// Interceptors returns the client interceptors.
func (c *LeagueClient) Interceptors() []Interceptor {
	return c.inters.League
}

func (c *LeagueClient) mutate(ctx context.Context, m *LeagueMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LeagueCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LeagueUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LeagueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LeagueDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown League mutation op: %q", m.Op())
	}
}

// LeagueMembershipClient is a client for the LeagueMembership schema.
type LeagueMembershipClient struct {
	config
}

// NewLeagueMembershipClient returns a client for the LeagueMembership from the given config.
func NewLeagueMembershipClient(c config) *LeagueMembershipClient {
	return &LeagueMembershipClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `leaguemembership.Hooks(f(g(h())))`.
func (c *LeagueMembershipClient) Use(hooks ...Hook) {
	c.hooks.LeagueMembership = append(c.hooks.LeagueMembership, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `leaguemembership.Intercept(f(g(h())))`.
func (c *LeagueMembershipClient) Intercept(interceptors ...Interceptor) {
	c.inters.LeagueMembership = append(c.inters.LeagueMembership, interceptors...)
}

// Create returns a builder for creating a LeagueMembership entity.
func (c *LeagueMembershipClient) Create() *LeagueMembershipCreate {
	mutation := newLeagueMembershipMutation(c.config, OpCreate)
	return &LeagueMembershipCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LeagueMembership entities.
func (c *LeagueMembershipClient) CreateBulk(builders ...*LeagueMembershipCreate) *LeagueMembershipCreateBulk {
	return &LeagueMembershipCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LeagueMembershipClient) MapCreateBulk(slice any, setFunc func(*LeagueMembershipCreate, int)) *LeagueMembershipCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LeagueMembershipCreateBulk{err: fmt.Errorf("calling to LeagueMembershipClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LeagueMembershipCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LeagueMembershipCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LeagueMembership.
func (c *LeagueMembershipClient) Update() *LeagueMembershipUpdate {
	mutation := newLeagueMembershipMutation(c.config, OpUpdate)
	return &LeagueMembershipUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LeagueMembershipClient) UpdateOne(_m *LeagueMembership) *LeagueMembershipUpdateOne {
	mutation := newLeagueMembershipMutation(c.config, OpUpdateOne, withLeagueMembership(_m))
	return &LeagueMembershipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LeagueMembershipClient) UpdateOneID(id uuid.UUID) *LeagueMembershipUpdateOne {
	mutation := newLeagueMembershipMutation(c.config, OpUpdateOne, withLeagueMembershipID(id))
	return &LeagueMembershipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LeagueMembership.
func (c *LeagueMembershipClient) Delete() *LeagueMembershipDelete {
	mutation := newLeagueMembershipMutation(c.config, OpDelete)
	return &LeagueMembershipDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LeagueMembershipClient) DeleteOne(_m *LeagueMembership) *LeagueMembershipDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LeagueMembershipClient) DeleteOneID(id uuid.UUID) *LeagueMembershipDeleteOne {
	builder := c.Delete().Where(leaguemembership.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LeagueMembershipDeleteOne{builder}
}

// Query returns a query builder for LeagueMembership.
func (c *LeagueMembershipClient) Query() *LeagueMembershipQuery {
	return &LeagueMembershipQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLeagueMembership},
		inters: c.Interceptors(),
	}
}

// Get returns a LeagueMembership entity by its id.
func (c *LeagueMembershipClient) Get(ctx context.Context, id uuid.UUID) (*LeagueMembership, error) {
	return c.Query().Where(leaguemembership.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LeagueMembershipClient) GetX(ctx context.Context, id uuid.UUID) *LeagueMembership {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a LeagueMembership.
func (c *LeagueMembershipClient) QueryUser(_m *LeagueMembership) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(leaguemembership.Table, leaguemembership.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, leaguemembership.UserTable, leaguemembership.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLeague queries the league edge of a LeagueMembership.
func (c *LeagueMembershipClient) QueryLeague(_m *LeagueMembership) *LeagueQuery {
	query := (&LeagueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(leaguemembership.Table, leaguemembership.FieldID, id),
			sqlgraph.To(league.Table, league.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, leaguemembership.LeagueTable, leaguemembership.LeagueColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LeagueMembershipClient) Hooks() []Hook {
	return c.hooks.LeagueMembership
}

// Interceptors returns the client interceptors.
func (c *LeagueMembershipClient) Interceptors() []Interceptor {
	return c.inters.LeagueMembership
}

func (c *LeagueMembershipClient) mutate(ctx context.Context, m *LeagueMembershipMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LeagueMembershipCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LeagueMembershipUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LeagueMembershipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LeagueMembershipDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LeagueMembership mutation op: %q", m.Op())
	}
}

// PickClient is a client for the Pick schema.
type PickClient struct {
	config
}

// NewPickClient returns a client for the Pick from the given config.
func NewPickClient(c config) *PickClient {
	return &PickClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pick.Hooks(f(g(h())))`.
func (c *PickClient) Use(hooks ...Hook) {
	c.hooks.Pick = append(c.hooks.Pick, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pick.Intercept(f(g(h())))`.
func (c *PickClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pick = append(c.inters.Pick, interceptors...)
}

// Create returns a builder for creating a Pick entity.
func (c *PickClient) Create() *PickCreate {
	mutation := newPickMutation(c.config, OpCreate)
	return &PickCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pick entities.
func (c *PickClient) CreateBulk(builders ...*PickCreate) *PickCreateBulk {
	return &PickCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PickClient) MapCreateBulk(slice any, setFunc func(*PickCreate, int)) *PickCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PickCreateBulk{err: fmt.Errorf("calling to PickClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PickCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PickCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pick.
func (c *PickClient) Update() *PickUpdate {
	mutation := newPickMutation(c.config, OpUpdate)
	return &PickUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PickClient) UpdateOne(_m *Pick) *PickUpdateOne {
	mutation := newPickMutation(c.config, OpUpdateOne, withPick(_m))
	return &PickUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PickClient) UpdateOneID(id uuid.UUID) *PickUpdateOne {
	mutation := newPickMutation(c.config, OpUpdateOne, withPickID(id))
	return &PickUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pick.
func (c *PickClient) Delete() *PickDelete {
	mutation := newPickMutation(c.config, OpDelete)
	return &PickDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PickClient) DeleteOne(_m *Pick) *PickDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PickClient) DeleteOneID(id uuid.UUID) *PickDeleteOne {
	builder := c.Delete().Where(pick.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PickDeleteOne{builder}
}

// Query returns a query builder for Pick.
func (c *PickClient) Query() *PickQuery {
	return &PickQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePick},
		inters: c.Interceptors(),
	}
}

// Get returns a Pick entity by its id.
func (c *PickClient) Get(ctx context.Context, id uuid.UUID) (*Pick, error) {
	return c.Query().Where(pick.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PickClient) GetX(ctx context.Context, id uuid.UUID) *Pick {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Pick.
func (c *PickClient) QueryUser(_m *Pick) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pick.Table, pick.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pick.UserTable, pick.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTournament queries the tournament edge of a Pick.
func (c *PickClient) QueryTournament(_m *Pick) *TournamentQuery {
	query := (&TournamentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pick.Table, pick.FieldID, id),
			sqlgraph.To(tournament.Table, tournament.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pick.TournamentTable, pick.TournamentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGolfer queries the golfer edge of a Pick.
func (c *PickClient) QueryGolfer(_m *Pick) *GolferQuery {
	query := (&GolferClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pick.Table, pick.FieldID, id),
			sqlgraph.To(golfer.Table, golfer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pick.GolferTable, pick.GolferColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLeague queries the league edge of a Pick.
func (c *PickClient) QueryLeague(_m *Pick) *LeagueQuery {
	query := (&LeagueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pick.Table, pick.FieldID, id),
			sqlgraph.To(league.Table, league.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pick.LeagueTable, pick.LeagueColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PickClient) Hooks() []Hook {
	return c.hooks.Pick
}

// Interceptors returns the client interceptors.
func (c *PickClient) Interceptors() []Interceptor {
	return c.inters.Pick
}

func (c *PickClient) mutate(ctx context.Context, m *PickMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PickCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PickUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PickUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PickDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pick mutation op: %q", m.Op())
	}
}

// SyncStatusClient is a client for the SyncStatus schema.
type SyncStatusClient struct {
	config
}

// NewSyncStatusClient returns a client for the SyncStatus from the given config.
func NewSyncStatusClient(c config) *SyncStatusClient {
	return &SyncStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `syncstatus.Hooks(f(g(h())))`.
func (c *SyncStatusClient) Use(hooks ...Hook) {
	c.hooks.SyncStatus = append(c.hooks.SyncStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `syncstatus.Intercept(f(g(h())))`.
func (c *SyncStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncStatus = append(c.inters.SyncStatus, interceptors...)
}

// Create returns a builder for creating a SyncStatus entity.
func (c *SyncStatusClient) Create() *SyncStatusCreate {
	mutation := newSyncStatusMutation(c.config, OpCreate)
	return &SyncStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncStatus entities.
func (c *SyncStatusClient) CreateBulk(builders ...*SyncStatusCreate) *SyncStatusCreateBulk {
	return &SyncStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncStatusClient) MapCreateBulk(slice any, setFunc func(*SyncStatusCreate, int)) *SyncStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncStatusCreateBulk{err: fmt.Errorf("calling to SyncStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncStatus.
func (c *SyncStatusClient) Update() *SyncStatusUpdate {
	mutation := newSyncStatusMutation(c.config, OpUpdate)
	return &SyncStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncStatusClient) UpdateOne(_m *SyncStatus) *SyncStatusUpdateOne {
	mutation := newSyncStatusMutation(c.config, OpUpdateOne, withSyncStatus(_m))
	return &SyncStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncStatusClient) UpdateOneID(id uuid.UUID) *SyncStatusUpdateOne {
	mutation := newSyncStatusMutation(c.config, OpUpdateOne, withSyncStatusID(id))
	return &SyncStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncStatus.
func (c *SyncStatusClient) Delete() *SyncStatusDelete {
	mutation := newSyncStatusMutation(c.config, OpDelete)
	return &SyncStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncStatusClient) DeleteOne(_m *SyncStatus) *SyncStatusDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncStatusClient) DeleteOneID(id uuid.UUID) *SyncStatusDeleteOne {
	builder := c.Delete().Where(syncstatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncStatusDeleteOne{builder}
}

// Query returns a query builder for SyncStatus.
func (c *SyncStatusClient) Query() *SyncStatusQuery {
	return &SyncStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncStatus entity by its id.
func (c *SyncStatusClient) Get(ctx context.Context, id uuid.UUID) (*SyncStatus, error) {
	return c.Query().Where(syncstatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncStatusClient) GetX(ctx context.Context, id uuid.UUID) *SyncStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SyncStatusClient) Hooks() []Hook {
	return c.hooks.SyncStatus
}

// Interceptors returns the client interceptors.
func (c *SyncStatusClient) Interceptors() []Interceptor {
	return c.inters.SyncStatus
}

func (c *SyncStatusClient) mutate(ctx context.Context, m *SyncStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncStatus mutation op: %q", m.Op())
	}
}

// TournamentClient is a client for the Tournament schema.
type TournamentClient struct {
	config
}

// NewTournamentClient returns a client for the Tournament from the given config.
func NewTournamentClient(c config) *TournamentClient {
	return &TournamentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tournament.Hooks(f(g(h())))`.
func (c *TournamentClient) Use(hooks ...Hook) {
	c.hooks.Tournament = append(c.hooks.Tournament, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tournament.Intercept(f(g(h())))`.
func (c *TournamentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tournament = append(c.inters.Tournament, interceptors...)
}

// Create returns a builder for creating a Tournament entity.
func (c *TournamentClient) Create() *TournamentCreate {
	mutation := newTournamentMutation(c.config, OpCreate)
	return &TournamentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tournament entities.
func (c *TournamentClient) CreateBulk(builders ...*TournamentCreate) *TournamentCreateBulk {
	return &TournamentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TournamentClient) MapCreateBulk(slice any, setFunc func(*TournamentCreate, int)) *TournamentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TournamentCreateBulk{err: fmt.Errorf("calling to TournamentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TournamentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TournamentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tournament.
func (c *TournamentClient) Update() *TournamentUpdate {
	mutation := newTournamentMutation(c.config, OpUpdate)
	return &TournamentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TournamentClient) UpdateOne(_m *Tournament) *TournamentUpdateOne {
	mutation := newTournamentMutation(c.config, OpUpdateOne, withTournament(_m))
	return &TournamentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TournamentClient) UpdateOneID(id uuid.UUID) *TournamentUpdateOne {
	mutation := newTournamentMutation(c.config, OpUpdateOne, withTournamentID(id))
	return &TournamentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tournament.
func (c *TournamentClient) Delete() *TournamentDelete {
	mutation := newTournamentMutation(c.config, OpDelete)
	return &TournamentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TournamentClient) DeleteOne(_m *Tournament) *TournamentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TournamentClient) DeleteOneID(id uuid.UUID) *TournamentDeleteOne {
	builder := c.Delete().Where(tournament.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TournamentDeleteOne{builder}
}

// Query returns a query builder for Tournament.
func (c *TournamentClient) Query() *TournamentQuery {
	return &TournamentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTournament},
		inters: c.Interceptors(),
	}
}

// Get returns a Tournament entity by its id.
func (c *TournamentClient) Get(ctx context.Context, id uuid.UUID) (*Tournament, error) {
	return c.Query().Where(tournament.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TournamentClient) GetX(ctx context.Context, id uuid.UUID) *Tournament {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPicks queries the picks edge of a Tournament.
func (c *TournamentClient) QueryPicks(_m *Tournament) *PickQuery {
	query := (&PickClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, id),
			sqlgraph.To(pick.Table, pick.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tournament.PicksTable, tournament.PicksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEntries queries the entries edge of a Tournament.
func (c *TournamentClient) QueryEntries(_m *Tournament) *TournamentEntryQuery {
	query := (&TournamentEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, id),
			sqlgraph.To(tournamententry.Table, tournamententry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tournament.EntriesTable, tournament.EntriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEmailReminders queries the email_reminders edge of a Tournament.
func (c *TournamentClient) QueryEmailReminders(_m *Tournament) *EmailReminderQuery {
	query := (&EmailReminderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, id),
			sqlgraph.To(emailreminder.Table, emailreminder.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tournament.EmailRemindersTable, tournament.EmailRemindersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChampion queries the champion edge of a Tournament.
func (c *TournamentClient) QueryChampion(_m *Tournament) *GolferQuery {
	query := (&GolferClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, id),
			sqlgraph.To(golfer.Table, golfer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tournament.ChampionTable, tournament.ChampionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TournamentClient) Hooks() []Hook {
	return c.hooks.Tournament
}

// Interceptors returns the client interceptors.
func (c *TournamentClient) Interceptors() []Interceptor {
	return c.inters.Tournament
}

func (c *TournamentClient) mutate(ctx context.Context, m *TournamentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TournamentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TournamentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TournamentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TournamentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tournament mutation op: %q", m.Op())
	}
}

// TournamentEntryClient is a client for the TournamentEntry schema.
type TournamentEntryClient struct {
	config
}

// NewTournamentEntryClient returns a client for the TournamentEntry from the given config.
func NewTournamentEntryClient(c config) *TournamentEntryClient {
	return &TournamentEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tournamententry.Hooks(f(g(h())))`.
func (c *TournamentEntryClient) Use(hooks ...Hook) {
	c.hooks.TournamentEntry = append(c.hooks.TournamentEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tournamententry.Intercept(f(g(h())))`.
func (c *TournamentEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.TournamentEntry = append(c.inters.TournamentEntry, interceptors...)
}

// Create returns a builder for creating a TournamentEntry entity.
func (c *TournamentEntryClient) Create() *TournamentEntryCreate {
	mutation := newTournamentEntryMutation(c.config, OpCreate)
	return &TournamentEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TournamentEntry entities.
func (c *TournamentEntryClient) CreateBulk(builders ...*TournamentEntryCreate) *TournamentEntryCreateBulk {
	return &TournamentEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TournamentEntryClient) MapCreateBulk(slice any, setFunc func(*TournamentEntryCreate, int)) *TournamentEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TournamentEntryCreateBulk{err: fmt.Errorf("calling to TournamentEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TournamentEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TournamentEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TournamentEntry.
func (c *TournamentEntryClient) Update() *TournamentEntryUpdate {
	mutation := newTournamentEntryMutation(c.config, OpUpdate)
	return &TournamentEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TournamentEntryClient) UpdateOne(_m *TournamentEntry) *TournamentEntryUpdateOne {
	mutation := newTournamentEntryMutation(c.config, OpUpdateOne, withTournamentEntry(_m))
	return &TournamentEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TournamentEntryClient) UpdateOneID(id uuid.UUID) *TournamentEntryUpdateOne {
	mutation := newTournamentEntryMutation(c.config, OpUpdateOne, withTournamentEntryID(id))
	return &TournamentEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TournamentEntry.
func (c *TournamentEntryClient) Delete() *TournamentEntryDelete {
	mutation := newTournamentEntryMutation(c.config, OpDelete)
	return &TournamentEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TournamentEntryClient) DeleteOne(_m *TournamentEntry) *TournamentEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TournamentEntryClient) DeleteOneID(id uuid.UUID) *TournamentEntryDeleteOne {
	builder := c.Delete().Where(tournamententry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TournamentEntryDeleteOne{builder}
}

// Query returns a query builder for TournamentEntry.
func (c *TournamentEntryClient) Query() *TournamentEntryQuery {
	return &TournamentEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTournamentEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a TournamentEntry entity by its id.
func (c *TournamentEntryClient) Get(ctx context.Context, id uuid.UUID) (*TournamentEntry, error) {
	return c.Query().Where(tournamententry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TournamentEntryClient) GetX(ctx context.Context, id uuid.UUID) *TournamentEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTournament queries the tournament edge of a TournamentEntry.
func (c *TournamentEntryClient) QueryTournament(_m *TournamentEntry) *TournamentQuery {
	query := (&TournamentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tournamententry.Table, tournamententry.FieldID, id),
			sqlgraph.To(tournament.Table, tournament.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tournamententry.TournamentTable, tournamententry.TournamentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGolfer queries the golfer edge of a TournamentEntry.
func (c *TournamentEntryClient) QueryGolfer(_m *TournamentEntry) *GolferQuery {
	query := (&GolferClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tournamententry.Table, tournamententry.FieldID, id),
			sqlgraph.To(golfer.Table, golfer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tournamententry.GolferTable, tournamententry.GolferColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TournamentEntryClient) Hooks() []Hook {
	return c.hooks.TournamentEntry
}

// Interceptors returns the client interceptors.
func (c *TournamentEntryClient) Interceptors() []Interceptor {
	return c.inters.TournamentEntry
}

func (c *TournamentEntryClient) mutate(ctx context.Context, m *TournamentEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TournamentEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TournamentEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TournamentEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TournamentEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TournamentEntry mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPicks queries the picks edge of a User.
func (c *UserClient) QueryPicks(_m *User) *PickQuery {
	query := (&PickClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(pick.Table, pick.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.PicksTable, user.PicksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLeagueMemberships queries the league_memberships edge of a User.
func (c *UserClient) QueryLeagueMemberships(_m *User) *LeagueMembershipQuery {
	query := (&LeagueMembershipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(leaguemembership.Table, leaguemembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.LeagueMembershipsTable, user.LeagueMembershipsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCommissionerActions queries the commissioner_actions edge of a User.
func (c *UserClient) QueryCommissionerActions(_m *User) *CommissionerActionQuery {
	query := (&CommissionerActionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(commissioneraction.Table, commissioneraction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CommissionerActionsTable, user.CommissionerActionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAffectedActions queries the affected_actions edge of a User.
func (c *UserClient) QueryAffectedActions(_m *User) *CommissionerActionQuery {
	query := (&CommissionerActionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(commissioneraction.Table, commissioneraction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AffectedActionsTable, user.AffectedActionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEmailReminders queries the email_reminders edge of a User.
func (c *UserClient) QueryEmailReminders(_m *User) *EmailReminderQuery {
	query := (&EmailReminderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(emailreminder.Table, emailreminder.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.EmailRemindersTable, user.EmailRemindersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CommissionerAction, EmailReminder, Golfer, League, LeagueMembership, Pick,
		SyncStatus, Tournament, TournamentEntry, User []ent.Hook
	}
	inters struct {
		CommissionerAction, EmailReminder, Golfer, League, LeagueMembership, Pick,
		SyncStatus, Tournament, TournamentEntry, User []ent.Interceptor
	}
)
