// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/course"
	"github.com/rj-davidson/greenrats/ent/coursehole"
)

// CourseHole is the model entity for the CourseHole schema.
type CourseHole struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// HoleNumber holds the value of the "hole_number" field.
	HoleNumber int `json:"hole_number,omitempty"`
	// Par holds the value of the "par" field.
	Par int `json:"par,omitempty"`
	// Yardage holds the value of the "yardage" field.
	Yardage *int `json:"yardage,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CourseHoleQuery when eager-loading is set.
	Edges        CourseHoleEdges `json:"edges"`
	course_holes *uuid.UUID
	selectValues sql.SelectValues
}

// CourseHoleEdges holds the relations/edges for other nodes in the graph.
type CourseHoleEdges struct {
	// Course holds the value of the course edge.
	Course *Course `json:"course,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CourseOrErr returns the Course value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseHoleEdges) CourseOrErr() (*Course, error) {
	if e.Course != nil {
		return e.Course, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: course.Label}
	}
	return nil, &NotLoadedError{edge: "course"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CourseHole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coursehole.FieldHoleNumber, coursehole.FieldPar, coursehole.FieldYardage:
			values[i] = new(sql.NullInt64)
		case coursehole.FieldID:
			values[i] = new(uuid.UUID)
		case coursehole.ForeignKeys[0]: // course_holes
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CourseHole fields.
func (_m *CourseHole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coursehole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case coursehole.FieldHoleNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hole_number", values[i])
			} else if value.Valid {
				_m.HoleNumber = int(value.Int64)
			}
		case coursehole.FieldPar:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field par", values[i])
			} else if value.Valid {
				_m.Par = int(value.Int64)
			}
		case coursehole.FieldYardage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field yardage", values[i])
			} else if value.Valid {
				_m.Yardage = new(int)
				*_m.Yardage = int(value.Int64)
			}
		case coursehole.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field course_holes", values[i])
			} else if value.Valid {
				_m.course_holes = new(uuid.UUID)
				*_m.course_holes = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CourseHole.
// This includes values selected through modifiers, order, etc.
func (_m *CourseHole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCourse queries the "course" edge of the CourseHole entity.
func (_m *CourseHole) QueryCourse() *CourseQuery {
	return NewCourseHoleClient(_m.config).QueryCourse(_m)
}

// Update returns a builder for updating this CourseHole.
// Note that you need to call CourseHole.Unwrap() before calling this method if this CourseHole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CourseHole) Update() *CourseHoleUpdateOne {
	return NewCourseHoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CourseHole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CourseHole) Unwrap() *CourseHole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CourseHole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CourseHole) String() string {
	var builder strings.Builder
	builder.WriteString("CourseHole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("hole_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.HoleNumber))
	builder.WriteString(", ")
	builder.WriteString("par=")
	builder.WriteString(fmt.Sprintf("%v", _m.Par))
	builder.WriteString(", ")
	if v := _m.Yardage; v != nil {
		builder.WriteString("yardage=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CourseHoles is a parsable slice of CourseHole.
type CourseHoles []*CourseHole
