// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/golfer"
	"github.com/rj-davidson/greenrats/ent/pick"
	"github.com/rj-davidson/greenrats/ent/predicate"
	"github.com/rj-davidson/greenrats/ent/tournamententry"
)

// GolferUpdate is the builder for updating Golfer entities.
type GolferUpdate struct {
	config
	hooks    []Hook
	mutation *GolferMutation
}

// Where appends a list predicates to the GolferUpdate builder.
func (_u *GolferUpdate) Where(ps ...predicate.Golfer) *GolferUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GolferUpdate) SetUpdatedAt(v time.Time) *GolferUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBdlID sets the "bdl_id" field.
func (_u *GolferUpdate) SetBdlID(v int) *GolferUpdate {
	_u.mutation.ResetBdlID()
	_u.mutation.SetBdlID(v)
	return _u
}

// SetNillableBdlID sets the "bdl_id" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableBdlID(v *int) *GolferUpdate {
	if v != nil {
		_u.SetBdlID(*v)
	}
	return _u
}

// AddBdlID adds value to the "bdl_id" field.
func (_u *GolferUpdate) AddBdlID(v int) *GolferUpdate {
	_u.mutation.AddBdlID(v)
	return _u
}

// ClearBdlID clears the value of the "bdl_id" field.
func (_u *GolferUpdate) ClearBdlID() *GolferUpdate {
	_u.mutation.ClearBdlID()
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *GolferUpdate) SetFirstName(v string) *GolferUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableFirstName(v *string) *GolferUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// ClearFirstName clears the value of the "first_name" field.
func (_u *GolferUpdate) ClearFirstName() *GolferUpdate {
	_u.mutation.ClearFirstName()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *GolferUpdate) SetLastName(v string) *GolferUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableLastName(v *string) *GolferUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// ClearLastName clears the value of the "last_name" field.
func (_u *GolferUpdate) ClearLastName() *GolferUpdate {
	_u.mutation.ClearLastName()
	return _u
}

// SetName sets the "name" field.
func (_u *GolferUpdate) SetName(v string) *GolferUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableName(v *string) *GolferUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *GolferUpdate) SetCountry(v string) *GolferUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableCountry(v *string) *GolferUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *GolferUpdate) ClearCountry() *GolferUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetCountryCode sets the "country_code" field.
func (_u *GolferUpdate) SetCountryCode(v string) *GolferUpdate {
	_u.mutation.SetCountryCode(v)
	return _u
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableCountryCode(v *string) *GolferUpdate {
	if v != nil {
		_u.SetCountryCode(*v)
	}
	return _u
}

// SetOwgr sets the "owgr" field.
func (_u *GolferUpdate) SetOwgr(v int) *GolferUpdate {
	_u.mutation.ResetOwgr()
	_u.mutation.SetOwgr(v)
	return _u
}

// SetNillableOwgr sets the "owgr" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableOwgr(v *int) *GolferUpdate {
	if v != nil {
		_u.SetOwgr(*v)
	}
	return _u
}

// AddOwgr adds value to the "owgr" field.
func (_u *GolferUpdate) AddOwgr(v int) *GolferUpdate {
	_u.mutation.AddOwgr(v)
	return _u
}

// ClearOwgr clears the value of the "owgr" field.
func (_u *GolferUpdate) ClearOwgr() *GolferUpdate {
	_u.mutation.ClearOwgr()
	return _u
}

// SetActive sets the "active" field.
func (_u *GolferUpdate) SetActive(v bool) *GolferUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableActive(v *bool) *GolferUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *GolferUpdate) SetImageURL(v string) *GolferUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *GolferUpdate) SetNillableImageURL(v *string) *GolferUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *GolferUpdate) ClearImageURL() *GolferUpdate {
	_u.mutation.ClearImageURL()
	return _u
}

// AddPickIDs adds the "picks" edge to the Pick entity by IDs.
func (_u *GolferUpdate) AddPickIDs(ids ...uuid.UUID) *GolferUpdate {
	_u.mutation.AddPickIDs(ids...)
	return _u
}

// AddPicks adds the "picks" edges to the Pick entity.
func (_u *GolferUpdate) AddPicks(v ...*Pick) *GolferUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPickIDs(ids...)
}

// AddEntryIDs adds the "entries" edge to the TournamentEntry entity by IDs.
func (_u *GolferUpdate) AddEntryIDs(ids ...uuid.UUID) *GolferUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the TournamentEntry entity.
func (_u *GolferUpdate) AddEntries(v ...*TournamentEntry) *GolferUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the GolferMutation object of the builder.
func (_u *GolferUpdate) Mutation() *GolferMutation {
	return _u.mutation
}

// ClearPicks clears all "picks" edges to the Pick entity.
func (_u *GolferUpdate) ClearPicks() *GolferUpdate {
	_u.mutation.ClearPicks()
	return _u
}

// RemovePickIDs removes the "picks" edge to Pick entities by IDs.
func (_u *GolferUpdate) RemovePickIDs(ids ...uuid.UUID) *GolferUpdate {
	_u.mutation.RemovePickIDs(ids...)
	return _u
}

// RemovePicks removes "picks" edges to Pick entities.
func (_u *GolferUpdate) RemovePicks(v ...*Pick) *GolferUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePickIDs(ids...)
}

// ClearEntries clears all "entries" edges to the TournamentEntry entity.
func (_u *GolferUpdate) ClearEntries() *GolferUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to TournamentEntry entities by IDs.
func (_u *GolferUpdate) RemoveEntryIDs(ids ...uuid.UUID) *GolferUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to TournamentEntry entities.
func (_u *GolferUpdate) RemoveEntries(v ...*TournamentEntry) *GolferUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GolferUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GolferUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GolferUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GolferUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GolferUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := golfer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GolferUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := golfer.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Golfer.name": %w`, err)}
		}
	}
	return nil
}

func (_u *GolferUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(golfer.Table, golfer.Columns, sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(golfer.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BdlID(); ok {
		_spec.SetField(golfer.FieldBdlID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBdlID(); ok {
		_spec.AddField(golfer.FieldBdlID, field.TypeInt, value)
	}
	if _u.mutation.BdlIDCleared() {
		_spec.ClearField(golfer.FieldBdlID, field.TypeInt)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(golfer.FieldFirstName, field.TypeString, value)
	}
	if _u.mutation.FirstNameCleared() {
		_spec.ClearField(golfer.FieldFirstName, field.TypeString)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(golfer.FieldLastName, field.TypeString, value)
	}
	if _u.mutation.LastNameCleared() {
		_spec.ClearField(golfer.FieldLastName, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(golfer.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(golfer.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(golfer.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.CountryCode(); ok {
		_spec.SetField(golfer.FieldCountryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owgr(); ok {
		_spec.SetField(golfer.FieldOwgr, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwgr(); ok {
		_spec.AddField(golfer.FieldOwgr, field.TypeInt, value)
	}
	if _u.mutation.OwgrCleared() {
		_spec.ClearField(golfer.FieldOwgr, field.TypeInt)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(golfer.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(golfer.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(golfer.FieldImageURL, field.TypeString)
	}
	if _u.mutation.PicksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.PicksTable,
			Columns: []string{golfer.PicksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPicksIDs(); len(nodes) > 0 && !_u.mutation.PicksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.PicksTable,
			Columns: []string{golfer.PicksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PicksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.PicksTable,
			Columns: []string{golfer.PicksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.EntriesTable,
			Columns: []string{golfer.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.EntriesTable,
			Columns: []string{golfer.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.EntriesTable,
			Columns: []string{golfer.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{golfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GolferUpdateOne is the builder for updating a single Golfer entity.
type GolferUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GolferMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GolferUpdateOne) SetUpdatedAt(v time.Time) *GolferUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBdlID sets the "bdl_id" field.
func (_u *GolferUpdateOne) SetBdlID(v int) *GolferUpdateOne {
	_u.mutation.ResetBdlID()
	_u.mutation.SetBdlID(v)
	return _u
}

// SetNillableBdlID sets the "bdl_id" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableBdlID(v *int) *GolferUpdateOne {
	if v != nil {
		_u.SetBdlID(*v)
	}
	return _u
}

// AddBdlID adds value to the "bdl_id" field.
func (_u *GolferUpdateOne) AddBdlID(v int) *GolferUpdateOne {
	_u.mutation.AddBdlID(v)
	return _u
}

// ClearBdlID clears the value of the "bdl_id" field.
func (_u *GolferUpdateOne) ClearBdlID() *GolferUpdateOne {
	_u.mutation.ClearBdlID()
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *GolferUpdateOne) SetFirstName(v string) *GolferUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableFirstName(v *string) *GolferUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// ClearFirstName clears the value of the "first_name" field.
func (_u *GolferUpdateOne) ClearFirstName() *GolferUpdateOne {
	_u.mutation.ClearFirstName()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *GolferUpdateOne) SetLastName(v string) *GolferUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableLastName(v *string) *GolferUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// ClearLastName clears the value of the "last_name" field.
func (_u *GolferUpdateOne) ClearLastName() *GolferUpdateOne {
	_u.mutation.ClearLastName()
	return _u
}

// SetName sets the "name" field.
func (_u *GolferUpdateOne) SetName(v string) *GolferUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableName(v *string) *GolferUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *GolferUpdateOne) SetCountry(v string) *GolferUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableCountry(v *string) *GolferUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *GolferUpdateOne) ClearCountry() *GolferUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetCountryCode sets the "country_code" field.
func (_u *GolferUpdateOne) SetCountryCode(v string) *GolferUpdateOne {
	_u.mutation.SetCountryCode(v)
	return _u
}

// SetNillableCountryCode sets the "country_code" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableCountryCode(v *string) *GolferUpdateOne {
	if v != nil {
		_u.SetCountryCode(*v)
	}
	return _u
}

// SetOwgr sets the "owgr" field.
func (_u *GolferUpdateOne) SetOwgr(v int) *GolferUpdateOne {
	_u.mutation.ResetOwgr()
	_u.mutation.SetOwgr(v)
	return _u
}

// SetNillableOwgr sets the "owgr" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableOwgr(v *int) *GolferUpdateOne {
	if v != nil {
		_u.SetOwgr(*v)
	}
	return _u
}

// AddOwgr adds value to the "owgr" field.
func (_u *GolferUpdateOne) AddOwgr(v int) *GolferUpdateOne {
	_u.mutation.AddOwgr(v)
	return _u
}

// ClearOwgr clears the value of the "owgr" field.
func (_u *GolferUpdateOne) ClearOwgr() *GolferUpdateOne {
	_u.mutation.ClearOwgr()
	return _u
}

// SetActive sets the "active" field.
func (_u *GolferUpdateOne) SetActive(v bool) *GolferUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableActive(v *bool) *GolferUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *GolferUpdateOne) SetImageURL(v string) *GolferUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *GolferUpdateOne) SetNillableImageURL(v *string) *GolferUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *GolferUpdateOne) ClearImageURL() *GolferUpdateOne {
	_u.mutation.ClearImageURL()
	return _u
}

// AddPickIDs adds the "picks" edge to the Pick entity by IDs.
func (_u *GolferUpdateOne) AddPickIDs(ids ...uuid.UUID) *GolferUpdateOne {
	_u.mutation.AddPickIDs(ids...)
	return _u
}

// AddPicks adds the "picks" edges to the Pick entity.
func (_u *GolferUpdateOne) AddPicks(v ...*Pick) *GolferUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPickIDs(ids...)
}

// AddEntryIDs adds the "entries" edge to the TournamentEntry entity by IDs.
func (_u *GolferUpdateOne) AddEntryIDs(ids ...uuid.UUID) *GolferUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the TournamentEntry entity.
func (_u *GolferUpdateOne) AddEntries(v ...*TournamentEntry) *GolferUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the GolferMutation object of the builder.
func (_u *GolferUpdateOne) Mutation() *GolferMutation {
	return _u.mutation
}

// ClearPicks clears all "picks" edges to the Pick entity.
func (_u *GolferUpdateOne) ClearPicks() *GolferUpdateOne {
	_u.mutation.ClearPicks()
	return _u
}

// RemovePickIDs removes the "picks" edge to Pick entities by IDs.
func (_u *GolferUpdateOne) RemovePickIDs(ids ...uuid.UUID) *GolferUpdateOne {
	_u.mutation.RemovePickIDs(ids...)
	return _u
}

// RemovePicks removes "picks" edges to Pick entities.
func (_u *GolferUpdateOne) RemovePicks(v ...*Pick) *GolferUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePickIDs(ids...)
}

// ClearEntries clears all "entries" edges to the TournamentEntry entity.
func (_u *GolferUpdateOne) ClearEntries() *GolferUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to TournamentEntry entities by IDs.
func (_u *GolferUpdateOne) RemoveEntryIDs(ids ...uuid.UUID) *GolferUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to TournamentEntry entities.
func (_u *GolferUpdateOne) RemoveEntries(v ...*TournamentEntry) *GolferUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Where appends a list predicates to the GolferUpdate builder.
func (_u *GolferUpdateOne) Where(ps ...predicate.Golfer) *GolferUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GolferUpdateOne) Select(field string, fields ...string) *GolferUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Golfer entity.
func (_u *GolferUpdateOne) Save(ctx context.Context) (*Golfer, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GolferUpdateOne) SaveX(ctx context.Context) *Golfer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GolferUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GolferUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GolferUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := golfer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GolferUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := golfer.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Golfer.name": %w`, err)}
		}
	}
	return nil
}

func (_u *GolferUpdateOne) sqlSave(ctx context.Context) (_node *Golfer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(golfer.Table, golfer.Columns, sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Golfer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, golfer.FieldID)
		for _, f := range fields {
			if !golfer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != golfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(golfer.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BdlID(); ok {
		_spec.SetField(golfer.FieldBdlID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBdlID(); ok {
		_spec.AddField(golfer.FieldBdlID, field.TypeInt, value)
	}
	if _u.mutation.BdlIDCleared() {
		_spec.ClearField(golfer.FieldBdlID, field.TypeInt)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(golfer.FieldFirstName, field.TypeString, value)
	}
	if _u.mutation.FirstNameCleared() {
		_spec.ClearField(golfer.FieldFirstName, field.TypeString)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(golfer.FieldLastName, field.TypeString, value)
	}
	if _u.mutation.LastNameCleared() {
		_spec.ClearField(golfer.FieldLastName, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(golfer.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(golfer.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(golfer.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.CountryCode(); ok {
		_spec.SetField(golfer.FieldCountryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owgr(); ok {
		_spec.SetField(golfer.FieldOwgr, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwgr(); ok {
		_spec.AddField(golfer.FieldOwgr, field.TypeInt, value)
	}
	if _u.mutation.OwgrCleared() {
		_spec.ClearField(golfer.FieldOwgr, field.TypeInt)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(golfer.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(golfer.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(golfer.FieldImageURL, field.TypeString)
	}
	if _u.mutation.PicksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.PicksTable,
			Columns: []string{golfer.PicksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPicksIDs(); len(nodes) > 0 && !_u.mutation.PicksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.PicksTable,
			Columns: []string{golfer.PicksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PicksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.PicksTable,
			Columns: []string{golfer.PicksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.EntriesTable,
			Columns: []string{golfer.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.EntriesTable,
			Columns: []string{golfer.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   golfer.EntriesTable,
			Columns: []string{golfer.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Golfer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{golfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
