// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/holescore"
	"github.com/rj-davidson/greenrats/ent/round"
)

// HoleScore is the model entity for the HoleScore schema.
type HoleScore struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// HoleNumber holds the value of the "hole_number" field.
	HoleNumber int `json:"hole_number,omitempty"`
	// Par holds the value of the "par" field.
	Par int `json:"par,omitempty"`
	// Player's score on this hole
	Score *int `json:"score,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HoleScoreQuery when eager-loading is set.
	Edges             HoleScoreEdges `json:"edges"`
	round_hole_scores *uuid.UUID
	selectValues      sql.SelectValues
}

// HoleScoreEdges holds the relations/edges for other nodes in the graph.
type HoleScoreEdges struct {
	// Round holds the value of the round edge.
	Round *Round `json:"round,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoundOrErr returns the Round value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HoleScoreEdges) RoundOrErr() (*Round, error) {
	if e.Round != nil {
		return e.Round, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: round.Label}
	}
	return nil, &NotLoadedError{edge: "round"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HoleScore) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case holescore.FieldHoleNumber, holescore.FieldPar, holescore.FieldScore:
			values[i] = new(sql.NullInt64)
		case holescore.FieldID:
			values[i] = new(uuid.UUID)
		case holescore.ForeignKeys[0]: // round_hole_scores
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HoleScore fields.
func (_m *HoleScore) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case holescore.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case holescore.FieldHoleNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hole_number", values[i])
			} else if value.Valid {
				_m.HoleNumber = int(value.Int64)
			}
		case holescore.FieldPar:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field par", values[i])
			} else if value.Valid {
				_m.Par = int(value.Int64)
			}
		case holescore.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = new(int)
				*_m.Score = int(value.Int64)
			}
		case holescore.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field round_hole_scores", values[i])
			} else if value.Valid {
				_m.round_hole_scores = new(uuid.UUID)
				*_m.round_hole_scores = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HoleScore.
// This includes values selected through modifiers, order, etc.
func (_m *HoleScore) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRound queries the "round" edge of the HoleScore entity.
func (_m *HoleScore) QueryRound() *RoundQuery {
	return NewHoleScoreClient(_m.config).QueryRound(_m)
}

// Update returns a builder for updating this HoleScore.
// Note that you need to call HoleScore.Unwrap() before calling this method if this HoleScore
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HoleScore) Update() *HoleScoreUpdateOne {
	return NewHoleScoreClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HoleScore entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HoleScore) Unwrap() *HoleScore {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HoleScore is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HoleScore) String() string {
	var builder strings.Builder
	builder.WriteString("HoleScore(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("hole_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.HoleNumber))
	builder.WriteString(", ")
	builder.WriteString("par=")
	builder.WriteString(fmt.Sprintf("%v", _m.Par))
	builder.WriteString(", ")
	if v := _m.Score; v != nil {
		builder.WriteString("score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// HoleScores is a parsable slice of HoleScore.
type HoleScores []*HoleScore
