// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/league"
	"github.com/rj-davidson/greenrats/ent/leaguemembership"
	"github.com/rj-davidson/greenrats/ent/user"
)

// LeagueMembershipCreate is the builder for creating a LeagueMembership entity.
type LeagueMembershipCreate struct {
	config
	mutation *LeagueMembershipMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LeagueMembershipCreate) SetCreatedAt(v time.Time) *LeagueMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LeagueMembershipCreate) SetNillableCreatedAt(v *time.Time) *LeagueMembershipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LeagueMembershipCreate) SetUpdatedAt(v time.Time) *LeagueMembershipCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LeagueMembershipCreate) SetNillableUpdatedAt(v *time.Time) *LeagueMembershipCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *LeagueMembershipCreate) SetRole(v leaguemembership.Role) *LeagueMembershipCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *LeagueMembershipCreate) SetNillableRole(v *leaguemembership.Role) *LeagueMembershipCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *LeagueMembershipCreate) SetJoinedAt(v time.Time) *LeagueMembershipCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *LeagueMembershipCreate) SetNillableJoinedAt(v *time.Time) *LeagueMembershipCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LeagueMembershipCreate) SetID(v uuid.UUID) *LeagueMembershipCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LeagueMembershipCreate) SetNillableID(v *uuid.UUID) *LeagueMembershipCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *LeagueMembershipCreate) SetUserID(id uuid.UUID) *LeagueMembershipCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *LeagueMembershipCreate) SetUser(v *User) *LeagueMembershipCreate {
	return _c.SetUserID(v.ID)
}

// SetLeagueID sets the "league" edge to the League entity by ID.
func (_c *LeagueMembershipCreate) SetLeagueID(id uuid.UUID) *LeagueMembershipCreate {
	_c.mutation.SetLeagueID(id)
	return _c
}

// SetLeague sets the "league" edge to the League entity.
func (_c *LeagueMembershipCreate) SetLeague(v *League) *LeagueMembershipCreate {
	return _c.SetLeagueID(v.ID)
}

// Mutation returns the LeagueMembershipMutation object of the builder.
func (_c *LeagueMembershipCreate) Mutation() *LeagueMembershipMutation {
	return _c.mutation
}

// Save creates the LeagueMembership in the database.
func (_c *LeagueMembershipCreate) Save(ctx context.Context) (*LeagueMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LeagueMembershipCreate) SaveX(ctx context.Context) *LeagueMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LeagueMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LeagueMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LeagueMembershipCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := leaguemembership.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := leaguemembership.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := leaguemembership.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := leaguemembership.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := leaguemembership.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LeagueMembershipCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LeagueMembership.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LeagueMembership.updated_at"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "LeagueMembership.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := leaguemembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "LeagueMembership.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "LeagueMembership.joined_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "LeagueMembership.user"`)}
	}
	if len(_c.mutation.LeagueIDs()) == 0 {
		return &ValidationError{Name: "league", err: errors.New(`ent: missing required edge "LeagueMembership.league"`)}
	}
	return nil
}

func (_c *LeagueMembershipCreate) sqlSave(ctx context.Context) (*LeagueMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LeagueMembershipCreate) createSpec() (*LeagueMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &LeagueMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(leaguemembership.Table, sqlgraph.NewFieldSpec(leaguemembership.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(leaguemembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(leaguemembership.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(leaguemembership.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(leaguemembership.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaguemembership.UserTable,
			Columns: []string{leaguemembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_league_memberships = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LeagueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaguemembership.LeagueTable,
			Columns: []string{leaguemembership.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.league_memberships = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LeagueMembershipCreateBulk is the builder for creating many LeagueMembership entities in bulk.
type LeagueMembershipCreateBulk struct {
	config
	err      error
	builders []*LeagueMembershipCreate
}

// Save creates the LeagueMembership entities in the database.
func (_c *LeagueMembershipCreateBulk) Save(ctx context.Context) ([]*LeagueMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LeagueMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LeagueMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LeagueMembershipCreateBulk) SaveX(ctx context.Context) []*LeagueMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LeagueMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LeagueMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
