// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/league"
	"github.com/rj-davidson/greenrats/ent/user"
)

// League is the model entity for the League schema.
type League struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Shareable join code
	Code string `json:"code,omitempty"`
	// SeasonYear holds the value of the "season_year" field.
	SeasonYear int `json:"season_year,omitempty"`
	// JoiningEnabled holds the value of the "joining_enabled" field.
	JoiningEnabled bool `json:"joining_enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LeagueQuery when eager-loading is set.
	Edges             LeagueEdges `json:"edges"`
	league_created_by *uuid.UUID
	selectValues      sql.SelectValues
}

// LeagueEdges holds the relations/edges for other nodes in the graph.
type LeagueEdges struct {
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// Memberships holds the value of the memberships edge.
	Memberships []*LeagueMembership `json:"memberships,omitempty"`
	// Picks holds the value of the picks edge.
	Picks []*Pick `json:"picks,omitempty"`
	// CommissionerActions holds the value of the commissioner_actions edge.
	CommissionerActions []*CommissionerAction `json:"commissioner_actions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeagueEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// MembershipsOrErr returns the Memberships value or an error if the edge
// was not loaded in eager-loading.
func (e LeagueEdges) MembershipsOrErr() ([]*LeagueMembership, error) {
	if e.loadedTypes[1] {
		return e.Memberships, nil
	}
	return nil, &NotLoadedError{edge: "memberships"}
}

// PicksOrErr returns the Picks value or an error if the edge
// was not loaded in eager-loading.
func (e LeagueEdges) PicksOrErr() ([]*Pick, error) {
	if e.loadedTypes[2] {
		return e.Picks, nil
	}
	return nil, &NotLoadedError{edge: "picks"}
}

// CommissionerActionsOrErr returns the CommissionerActions value or an error if the edge
// was not loaded in eager-loading.
func (e LeagueEdges) CommissionerActionsOrErr() ([]*CommissionerAction, error) {
	if e.loadedTypes[3] {
		return e.CommissionerActions, nil
	}
	return nil, &NotLoadedError{edge: "commissioner_actions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*League) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case league.FieldJoiningEnabled:
			values[i] = new(sql.NullBool)
		case league.FieldSeasonYear:
			values[i] = new(sql.NullInt64)
		case league.FieldName, league.FieldCode:
			values[i] = new(sql.NullString)
		case league.FieldCreatedAt, league.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case league.FieldID:
			values[i] = new(uuid.UUID)
		case league.ForeignKeys[0]: // league_created_by
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the League fields.
func (_m *League) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case league.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case league.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case league.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case league.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case league.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case league.FieldSeasonYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field season_year", values[i])
			} else if value.Valid {
				_m.SeasonYear = int(value.Int64)
			}
		case league.FieldJoiningEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field joining_enabled", values[i])
			} else if value.Valid {
				_m.JoiningEnabled = value.Bool
			}
		case league.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field league_created_by", values[i])
			} else if value.Valid {
				_m.league_created_by = new(uuid.UUID)
				*_m.league_created_by = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the League.
// This includes values selected through modifiers, order, etc.
func (_m *League) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreatedBy queries the "created_by" edge of the League entity.
func (_m *League) QueryCreatedBy() *UserQuery {
	return NewLeagueClient(_m.config).QueryCreatedBy(_m)
}

// QueryMemberships queries the "memberships" edge of the League entity.
func (_m *League) QueryMemberships() *LeagueMembershipQuery {
	return NewLeagueClient(_m.config).QueryMemberships(_m)
}

// QueryPicks queries the "picks" edge of the League entity.
func (_m *League) QueryPicks() *PickQuery {
	return NewLeagueClient(_m.config).QueryPicks(_m)
}

// QueryCommissionerActions queries the "commissioner_actions" edge of the League entity.
func (_m *League) QueryCommissionerActions() *CommissionerActionQuery {
	return NewLeagueClient(_m.config).QueryCommissionerActions(_m)
}

// Update returns a builder for updating this League.
// Note that you need to call League.Unwrap() before calling this method if this League
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *League) Update() *LeagueUpdateOne {
	return NewLeagueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the League entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *League) Unwrap() *League {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: League is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *League) String() string {
	var builder strings.Builder
	builder.WriteString("League(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("season_year=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeasonYear))
	builder.WriteString(", ")
	builder.WriteString("joining_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.JoiningEnabled))
	builder.WriteByte(')')
	return builder.String()
}

// Leagues is a parsable slice of League.
type Leagues []*League
