// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/rj-davidson/greenrats/ent/league"
	"github.com/rj-davidson/greenrats/ent/leaguemembership"
	"github.com/rj-davidson/greenrats/ent/pick"
	"github.com/rj-davidson/greenrats/ent/user"
)

// LeagueCreate is the builder for creating a League entity.
type LeagueCreate struct {
	config
	mutation *LeagueMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LeagueCreate) SetCreatedAt(v time.Time) *LeagueCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LeagueCreate) SetNillableCreatedAt(v *time.Time) *LeagueCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LeagueCreate) SetUpdatedAt(v time.Time) *LeagueCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LeagueCreate) SetNillableUpdatedAt(v *time.Time) *LeagueCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *LeagueCreate) SetName(v string) *LeagueCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *LeagueCreate) SetCode(v string) *LeagueCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetSeasonYear sets the "season_year" field.
func (_c *LeagueCreate) SetSeasonYear(v int) *LeagueCreate {
	_c.mutation.SetSeasonYear(v)
	return _c
}

// SetID sets the "id" field.
func (_c *LeagueCreate) SetID(v uuid.UUID) *LeagueCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LeagueCreate) SetNillableID(v *uuid.UUID) *LeagueCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *LeagueCreate) SetCreatedByID(id uuid.UUID) *LeagueCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *LeagueCreate) SetCreatedBy(v *User) *LeagueCreate {
	return _c.SetCreatedByID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the LeagueMembership entity by IDs.
func (_c *LeagueCreate) AddMembershipIDs(ids ...uuid.UUID) *LeagueCreate {
	_c.mutation.AddMembershipIDs(ids...)
	return _c
}

// AddMemberships adds the "memberships" edges to the LeagueMembership entity.
func (_c *LeagueCreate) AddMemberships(v ...*LeagueMembership) *LeagueCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipIDs(ids...)
}

// AddPickIDs adds the "picks" edge to the Pick entity by IDs.
func (_c *LeagueCreate) AddPickIDs(ids ...uuid.UUID) *LeagueCreate {
	_c.mutation.AddPickIDs(ids...)
	return _c
}

// AddPicks adds the "picks" edges to the Pick entity.
func (_c *LeagueCreate) AddPicks(v ...*Pick) *LeagueCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPickIDs(ids...)
}

// Mutation returns the LeagueMutation object of the builder.
func (_c *LeagueCreate) Mutation() *LeagueMutation {
	return _c.mutation
}

// Save creates the League in the database.
func (_c *LeagueCreate) Save(ctx context.Context) (*League, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LeagueCreate) SaveX(ctx context.Context) *League {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LeagueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LeagueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LeagueCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := league.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := league.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := league.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LeagueCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "League.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "League.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "League.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := league.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "League.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "League.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := league.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "League.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SeasonYear(); !ok {
		return &ValidationError{Name: "season_year", err: errors.New(`ent: missing required field "League.season_year"`)}
	}
	if len(_c.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "League.created_by"`)}
	}
	return nil
}

func (_c *LeagueCreate) sqlSave(ctx context.Context) (*League, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LeagueCreate) createSpec() (*League, *sqlgraph.CreateSpec) {
	var (
		_node = &League{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(league.Table, sqlgraph.NewFieldSpec(league.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(league.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(league.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(league.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(league.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.SeasonYear(); ok {
		_spec.SetField(league.FieldSeasonYear, field.TypeInt, value)
		_node.SeasonYear = value
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   league.CreatedByTable,
			Columns: []string{league.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.league_created_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   league.MembershipsTable,
			Columns: []string{league.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaguemembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PicksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   league.PicksTable,
			Columns: []string{league.PicksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LeagueCreateBulk is the builder for creating many League entities in bulk.
type LeagueCreateBulk struct {
	config
	err      error
	builders []*LeagueCreate
}

// Save creates the League entities in the database.
func (_c *LeagueCreateBulk) Save(ctx context.Context) ([]*League, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*League, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LeagueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LeagueCreateBulk) SaveX(ctx context.Context) []*League {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LeagueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LeagueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
