// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/league"
	"github.com/rj-davidson/greenrats/ent/leaguemembership"
	"github.com/rj-davidson/greenrats/ent/pick"
	"github.com/rj-davidson/greenrats/ent/predicate"
	"github.com/rj-davidson/greenrats/ent/user"
)

// LeagueQuery is the builder for querying League entities.
type LeagueQuery struct {
	config
	ctx             *QueryContext
	order           []league.OrderOption
	inters          []Interceptor
	predicates      []predicate.League
	withCreatedBy   *UserQuery
	withMemberships *LeagueMembershipQuery
	withPicks       *PickQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LeagueQuery builder.
func (_q *LeagueQuery) Where(ps ...predicate.League) *LeagueQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LeagueQuery) Limit(limit int) *LeagueQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LeagueQuery) Offset(offset int) *LeagueQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LeagueQuery) Unique(unique bool) *LeagueQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LeagueQuery) Order(o ...league.OrderOption) *LeagueQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCreatedBy chains the current query on the "created_by" edge.
func (_q *LeagueQuery) QueryCreatedBy() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, league.CreatedByTable, league.CreatedByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMemberships chains the current query on the "memberships" edge.
func (_q *LeagueQuery) QueryMemberships() *LeagueMembershipQuery {
	query := (&LeagueMembershipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, selector),
			sqlgraph.To(leaguemembership.Table, leaguemembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, league.MembershipsTable, league.MembershipsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPicks chains the current query on the "picks" edge.
func (_q *LeagueQuery) QueryPicks() *PickQuery {
	query := (&PickClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, selector),
			sqlgraph.To(pick.Table, pick.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, league.PicksTable, league.PicksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first League entity from the query.
// Returns a *NotFoundError when no League was found.
func (_q *LeagueQuery) First(ctx context.Context) (*League, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{league.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LeagueQuery) FirstX(ctx context.Context) *League {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first League ID from the query.
// Returns a *NotFoundError when no League ID was found.
func (_q *LeagueQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{league.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LeagueQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single League entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one League entity is found.
// Returns a *NotFoundError when no League entities are found.
func (_q *LeagueQuery) Only(ctx context.Context) (*League, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{league.Label}
	default:
		return nil, &NotSingularError{league.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LeagueQuery) OnlyX(ctx context.Context) *League {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only League ID in the query.
// Returns a *NotSingularError when more than one League ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LeagueQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{league.Label}
	default:
		err = &NotSingularError{league.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LeagueQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Leagues.
func (_q *LeagueQuery) All(ctx context.Context) ([]*League, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*League, *LeagueQuery]()
	return withInterceptors[[]*League](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LeagueQuery) AllX(ctx context.Context) []*League {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of League IDs.
func (_q *LeagueQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(league.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LeagueQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LeagueQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LeagueQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LeagueQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LeagueQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LeagueQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LeagueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LeagueQuery) Clone() *LeagueQuery {
	if _q == nil {
		return nil
	}
	return &LeagueQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]league.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.League{}, _q.predicates...),
		withCreatedBy:   _q.withCreatedBy.Clone(),
		withMemberships: _q.withMemberships.Clone(),
		withPicks:       _q.withPicks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCreatedBy tells the query-builder to eager-load the nodes that are connected to
// the "created_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LeagueQuery) WithCreatedBy(opts ...func(*UserQuery)) *LeagueQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreatedBy = query
	return _q
}

// WithMemberships tells the query-builder to eager-load the nodes that are connected to
// the "memberships" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LeagueQuery) WithMemberships(opts ...func(*LeagueMembershipQuery)) *LeagueQuery {
	query := (&LeagueMembershipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMemberships = query
	return _q
}

// WithPicks tells the query-builder to eager-load the nodes that are connected to
// the "picks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LeagueQuery) WithPicks(opts ...func(*PickQuery)) *LeagueQuery {
	query := (&PickClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPicks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.League.Query().
//		GroupBy(league.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LeagueQuery) GroupBy(field string, fields ...string) *LeagueGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LeagueGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = league.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.League.Query().
//		Select(league.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *LeagueQuery) Select(fields ...string) *LeagueSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LeagueSelect{LeagueQuery: _q}
	sbuild.label = league.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LeagueSelect configured with the given aggregations.
func (_q *LeagueQuery) Aggregate(fns ...AggregateFunc) *LeagueSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LeagueQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !league.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LeagueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*League, error) {
	var (
		nodes       = []*League{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withCreatedBy != nil,
			_q.withMemberships != nil,
			_q.withPicks != nil,
		}
	)
	if _q.withCreatedBy != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, league.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*League).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &League{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCreatedBy; query != nil {
		if err := _q.loadCreatedBy(ctx, query, nodes, nil,
			func(n *League, e *User) { n.Edges.CreatedBy = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMemberships; query != nil {
		if err := _q.loadMemberships(ctx, query, nodes,
			func(n *League) { n.Edges.Memberships = []*LeagueMembership{} },
			func(n *League, e *LeagueMembership) { n.Edges.Memberships = append(n.Edges.Memberships, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPicks; query != nil {
		if err := _q.loadPicks(ctx, query, nodes,
			func(n *League) { n.Edges.Picks = []*Pick{} },
			func(n *League, e *Pick) { n.Edges.Picks = append(n.Edges.Picks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LeagueQuery) loadCreatedBy(ctx context.Context, query *UserQuery, nodes []*League, init func(*League), assign func(*League, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*League)
	for i := range nodes {
		if nodes[i].league_created_by == nil {
			continue
		}
		fk := *nodes[i].league_created_by
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "league_created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LeagueQuery) loadMemberships(ctx context.Context, query *LeagueMembershipQuery, nodes []*League, init func(*League), assign func(*League, *LeagueMembership)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*League)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.LeagueMembership(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(league.MembershipsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.league_memberships
		if fk == nil {
			return fmt.Errorf(`foreign-key "league_memberships" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "league_memberships" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *LeagueQuery) loadPicks(ctx context.Context, query *PickQuery, nodes []*League, init func(*League), assign func(*League, *Pick)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*League)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Pick(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(league.PicksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.league_picks
		if fk == nil {
			return fmt.Errorf(`foreign-key "league_picks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "league_picks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *LeagueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LeagueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(league.Table, league.Columns, sqlgraph.NewFieldSpec(league.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, league.FieldID)
		for i := range fields {
			if fields[i] != league.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LeagueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(league.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = league.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LeagueGroupBy is the group-by builder for League entities.
type LeagueGroupBy struct {
	selector
	build *LeagueQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LeagueGroupBy) Aggregate(fns ...AggregateFunc) *LeagueGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LeagueGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LeagueQuery, *LeagueGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LeagueGroupBy) sqlScan(ctx context.Context, root *LeagueQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LeagueSelect is the builder for selecting fields of League entities.
type LeagueSelect struct {
	*LeagueQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LeagueSelect) Aggregate(fns ...AggregateFunc) *LeagueSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LeagueSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LeagueQuery, *LeagueSelect](ctx, _s.LeagueQuery, _s, _s.inters, v)
}

func (_s *LeagueSelect) sqlScan(ctx context.Context, root *LeagueQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
