// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/golfer"
	"github.com/rj-davidson/greenrats/ent/league"
	"github.com/rj-davidson/greenrats/ent/pick"
	"github.com/rj-davidson/greenrats/ent/predicate"
	"github.com/rj-davidson/greenrats/ent/tournament"
	"github.com/rj-davidson/greenrats/ent/user"
)

// PickUpdate is the builder for updating Pick entities.
type PickUpdate struct {
	config
	hooks    []Hook
	mutation *PickMutation
}

// Where appends a list predicates to the PickUpdate builder.
func (_u *PickUpdate) Where(ps ...predicate.Pick) *PickUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSeasonYear sets the "season_year" field.
func (_u *PickUpdate) SetSeasonYear(v int) *PickUpdate {
	_u.mutation.ResetSeasonYear()
	_u.mutation.SetSeasonYear(v)
	return _u
}

// SetNillableSeasonYear sets the "season_year" field if the given value is not nil.
func (_u *PickUpdate) SetNillableSeasonYear(v *int) *PickUpdate {
	if v != nil {
		_u.SetSeasonYear(*v)
	}
	return _u
}

// AddSeasonYear adds value to the "season_year" field.
func (_u *PickUpdate) AddSeasonYear(v int) *PickUpdate {
	_u.mutation.AddSeasonYear(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PickUpdate) SetUserID(id uuid.UUID) *PickUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PickUpdate) SetUser(v *User) *PickUpdate {
	return _u.SetUserID(v.ID)
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_u *PickUpdate) SetTournamentID(id uuid.UUID) *PickUpdate {
	_u.mutation.SetTournamentID(id)
	return _u
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_u *PickUpdate) SetTournament(v *Tournament) *PickUpdate {
	return _u.SetTournamentID(v.ID)
}

// SetGolferID sets the "golfer" edge to the Golfer entity by ID.
func (_u *PickUpdate) SetGolferID(id uuid.UUID) *PickUpdate {
	_u.mutation.SetGolferID(id)
	return _u
}

// SetGolfer sets the "golfer" edge to the Golfer entity.
func (_u *PickUpdate) SetGolfer(v *Golfer) *PickUpdate {
	return _u.SetGolferID(v.ID)
}

// SetLeagueID sets the "league" edge to the League entity by ID.
func (_u *PickUpdate) SetLeagueID(id uuid.UUID) *PickUpdate {
	_u.mutation.SetLeagueID(id)
	return _u
}

// SetLeague sets the "league" edge to the League entity.
func (_u *PickUpdate) SetLeague(v *League) *PickUpdate {
	return _u.SetLeagueID(v.ID)
}

// Mutation returns the PickMutation object of the builder.
func (_u *PickUpdate) Mutation() *PickMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PickUpdate) ClearUser() *PickUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTournament clears the "tournament" edge to the Tournament entity.
func (_u *PickUpdate) ClearTournament() *PickUpdate {
	_u.mutation.ClearTournament()
	return _u
}

// ClearGolfer clears the "golfer" edge to the Golfer entity.
func (_u *PickUpdate) ClearGolfer() *PickUpdate {
	_u.mutation.ClearGolfer()
	return _u
}

// ClearLeague clears the "league" edge to the League entity.
func (_u *PickUpdate) ClearLeague() *PickUpdate {
	_u.mutation.ClearLeague()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PickUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PickUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PickUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PickUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PickUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.user"`)
	}
	if _u.mutation.TournamentCleared() && len(_u.mutation.TournamentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.tournament"`)
	}
	if _u.mutation.GolferCleared() && len(_u.mutation.GolferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.golfer"`)
	}
	if _u.mutation.LeagueCleared() && len(_u.mutation.LeagueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.league"`)
	}
	return nil
}

func (_u *PickUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pick.Table, pick.Columns, sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SeasonYear(); ok {
		_spec.SetField(pick.FieldSeasonYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeasonYear(); ok {
		_spec.AddField(pick.FieldSeasonYear, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.UserTable,
			Columns: []string{pick.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.UserTable,
			Columns: []string{pick.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TournamentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.TournamentTable,
			Columns: []string{pick.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.TournamentTable,
			Columns: []string{pick.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GolferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.GolferTable,
			Columns: []string{pick.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GolferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.GolferTable,
			Columns: []string{pick.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeagueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.LeagueTable,
			Columns: []string{pick.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeagueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.LeagueTable,
			Columns: []string{pick.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pick.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PickUpdateOne is the builder for updating a single Pick entity.
type PickUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PickMutation
}

// SetSeasonYear sets the "season_year" field.
func (_u *PickUpdateOne) SetSeasonYear(v int) *PickUpdateOne {
	_u.mutation.ResetSeasonYear()
	_u.mutation.SetSeasonYear(v)
	return _u
}

// SetNillableSeasonYear sets the "season_year" field if the given value is not nil.
func (_u *PickUpdateOne) SetNillableSeasonYear(v *int) *PickUpdateOne {
	if v != nil {
		_u.SetSeasonYear(*v)
	}
	return _u
}

// AddSeasonYear adds value to the "season_year" field.
func (_u *PickUpdateOne) AddSeasonYear(v int) *PickUpdateOne {
	_u.mutation.AddSeasonYear(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PickUpdateOne) SetUserID(id uuid.UUID) *PickUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PickUpdateOne) SetUser(v *User) *PickUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_u *PickUpdateOne) SetTournamentID(id uuid.UUID) *PickUpdateOne {
	_u.mutation.SetTournamentID(id)
	return _u
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_u *PickUpdateOne) SetTournament(v *Tournament) *PickUpdateOne {
	return _u.SetTournamentID(v.ID)
}

// SetGolferID sets the "golfer" edge to the Golfer entity by ID.
func (_u *PickUpdateOne) SetGolferID(id uuid.UUID) *PickUpdateOne {
	_u.mutation.SetGolferID(id)
	return _u
}

// SetGolfer sets the "golfer" edge to the Golfer entity.
func (_u *PickUpdateOne) SetGolfer(v *Golfer) *PickUpdateOne {
	return _u.SetGolferID(v.ID)
}

// SetLeagueID sets the "league" edge to the League entity by ID.
func (_u *PickUpdateOne) SetLeagueID(id uuid.UUID) *PickUpdateOne {
	_u.mutation.SetLeagueID(id)
	return _u
}

// SetLeague sets the "league" edge to the League entity.
func (_u *PickUpdateOne) SetLeague(v *League) *PickUpdateOne {
	return _u.SetLeagueID(v.ID)
}

// Mutation returns the PickMutation object of the builder.
func (_u *PickUpdateOne) Mutation() *PickMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PickUpdateOne) ClearUser() *PickUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTournament clears the "tournament" edge to the Tournament entity.
func (_u *PickUpdateOne) ClearTournament() *PickUpdateOne {
	_u.mutation.ClearTournament()
	return _u
}

// ClearGolfer clears the "golfer" edge to the Golfer entity.
func (_u *PickUpdateOne) ClearGolfer() *PickUpdateOne {
	_u.mutation.ClearGolfer()
	return _u
}

// ClearLeague clears the "league" edge to the League entity.
func (_u *PickUpdateOne) ClearLeague() *PickUpdateOne {
	_u.mutation.ClearLeague()
	return _u
}

// Where appends a list predicates to the PickUpdate builder.
func (_u *PickUpdateOne) Where(ps ...predicate.Pick) *PickUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PickUpdateOne) Select(field string, fields ...string) *PickUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pick entity.
func (_u *PickUpdateOne) Save(ctx context.Context) (*Pick, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PickUpdateOne) SaveX(ctx context.Context) *Pick {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PickUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PickUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PickUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.user"`)
	}
	if _u.mutation.TournamentCleared() && len(_u.mutation.TournamentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.tournament"`)
	}
	if _u.mutation.GolferCleared() && len(_u.mutation.GolferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.golfer"`)
	}
	if _u.mutation.LeagueCleared() && len(_u.mutation.LeagueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pick.league"`)
	}
	return nil
}

func (_u *PickUpdateOne) sqlSave(ctx context.Context) (_node *Pick, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pick.Table, pick.Columns, sqlgraph.NewFieldSpec(pick.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pick.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pick.FieldID)
		for _, f := range fields {
			if !pick.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pick.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SeasonYear(); ok {
		_spec.SetField(pick.FieldSeasonYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeasonYear(); ok {
		_spec.AddField(pick.FieldSeasonYear, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.UserTable,
			Columns: []string{pick.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.UserTable,
			Columns: []string{pick.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TournamentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.TournamentTable,
			Columns: []string{pick.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.TournamentTable,
			Columns: []string{pick.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GolferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.GolferTable,
			Columns: []string{pick.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GolferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.GolferTable,
			Columns: []string{pick.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeagueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.LeagueTable,
			Columns: []string{pick.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeagueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pick.LeagueTable,
			Columns: []string{pick.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pick{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pick.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
