// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/golfer"
	"github.com/rj-davidson/greenrats/ent/predicate"
	"github.com/rj-davidson/greenrats/ent/tournament"
	"github.com/rj-davidson/greenrats/ent/tournamententry"
)

// TournamentEntryUpdate is the builder for updating TournamentEntry entities.
type TournamentEntryUpdate struct {
	config
	hooks    []Hook
	mutation *TournamentEntryMutation
}

// Where appends a list predicates to the TournamentEntryUpdate builder.
func (_u *TournamentEntryUpdate) Where(ps ...predicate.TournamentEntry) *TournamentEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TournamentEntryUpdate) SetUpdatedAt(v time.Time) *TournamentEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *TournamentEntryUpdate) SetPosition(v int) *TournamentEntryUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillablePosition(v *int) *TournamentEntryUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *TournamentEntryUpdate) AddPosition(v int) *TournamentEntryUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetCut sets the "cut" field.
func (_u *TournamentEntryUpdate) SetCut(v bool) *TournamentEntryUpdate {
	_u.mutation.SetCut(v)
	return _u
}

// SetNillableCut sets the "cut" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillableCut(v *bool) *TournamentEntryUpdate {
	if v != nil {
		_u.SetCut(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *TournamentEntryUpdate) SetScore(v int) *TournamentEntryUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillableScore(v *int) *TournamentEntryUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *TournamentEntryUpdate) AddScore(v int) *TournamentEntryUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetTotalStrokes sets the "total_strokes" field.
func (_u *TournamentEntryUpdate) SetTotalStrokes(v int) *TournamentEntryUpdate {
	_u.mutation.ResetTotalStrokes()
	_u.mutation.SetTotalStrokes(v)
	return _u
}

// SetNillableTotalStrokes sets the "total_strokes" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillableTotalStrokes(v *int) *TournamentEntryUpdate {
	if v != nil {
		_u.SetTotalStrokes(*v)
	}
	return _u
}

// AddTotalStrokes adds value to the "total_strokes" field.
func (_u *TournamentEntryUpdate) AddTotalStrokes(v int) *TournamentEntryUpdate {
	_u.mutation.AddTotalStrokes(v)
	return _u
}

// SetEarnings sets the "earnings" field.
func (_u *TournamentEntryUpdate) SetEarnings(v int) *TournamentEntryUpdate {
	_u.mutation.ResetEarnings()
	_u.mutation.SetEarnings(v)
	return _u
}

// SetNillableEarnings sets the "earnings" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillableEarnings(v *int) *TournamentEntryUpdate {
	if v != nil {
		_u.SetEarnings(*v)
	}
	return _u
}

// AddEarnings adds value to the "earnings" field.
func (_u *TournamentEntryUpdate) AddEarnings(v int) *TournamentEntryUpdate {
	_u.mutation.AddEarnings(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TournamentEntryUpdate) SetStatus(v tournamententry.Status) *TournamentEntryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillableStatus(v *tournamententry.Status) *TournamentEntryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentRound sets the "current_round" field.
func (_u *TournamentEntryUpdate) SetCurrentRound(v int) *TournamentEntryUpdate {
	_u.mutation.ResetCurrentRound()
	_u.mutation.SetCurrentRound(v)
	return _u
}

// SetNillableCurrentRound sets the "current_round" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillableCurrentRound(v *int) *TournamentEntryUpdate {
	if v != nil {
		_u.SetCurrentRound(*v)
	}
	return _u
}

// AddCurrentRound adds value to the "current_round" field.
func (_u *TournamentEntryUpdate) AddCurrentRound(v int) *TournamentEntryUpdate {
	_u.mutation.AddCurrentRound(v)
	return _u
}

// SetThru sets the "thru" field.
func (_u *TournamentEntryUpdate) SetThru(v int) *TournamentEntryUpdate {
	_u.mutation.ResetThru()
	_u.mutation.SetThru(v)
	return _u
}

// SetNillableThru sets the "thru" field if the given value is not nil.
func (_u *TournamentEntryUpdate) SetNillableThru(v *int) *TournamentEntryUpdate {
	if v != nil {
		_u.SetThru(*v)
	}
	return _u
}

// AddThru adds value to the "thru" field.
func (_u *TournamentEntryUpdate) AddThru(v int) *TournamentEntryUpdate {
	_u.mutation.AddThru(v)
	return _u
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_u *TournamentEntryUpdate) SetTournamentID(id uuid.UUID) *TournamentEntryUpdate {
	_u.mutation.SetTournamentID(id)
	return _u
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_u *TournamentEntryUpdate) SetTournament(v *Tournament) *TournamentEntryUpdate {
	return _u.SetTournamentID(v.ID)
}

// SetGolferID sets the "golfer" edge to the Golfer entity by ID.
func (_u *TournamentEntryUpdate) SetGolferID(id uuid.UUID) *TournamentEntryUpdate {
	_u.mutation.SetGolferID(id)
	return _u
}

// SetGolfer sets the "golfer" edge to the Golfer entity.
func (_u *TournamentEntryUpdate) SetGolfer(v *Golfer) *TournamentEntryUpdate {
	return _u.SetGolferID(v.ID)
}

// Mutation returns the TournamentEntryMutation object of the builder.
func (_u *TournamentEntryUpdate) Mutation() *TournamentEntryMutation {
	return _u.mutation
}

// ClearTournament clears the "tournament" edge to the Tournament entity.
func (_u *TournamentEntryUpdate) ClearTournament() *TournamentEntryUpdate {
	_u.mutation.ClearTournament()
	return _u
}

// ClearGolfer clears the "golfer" edge to the Golfer entity.
func (_u *TournamentEntryUpdate) ClearGolfer() *TournamentEntryUpdate {
	_u.mutation.ClearGolfer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TournamentEntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TournamentEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TournamentEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TournamentEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TournamentEntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tournamententry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TournamentEntryUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := tournamententry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TournamentEntry.status": %w`, err)}
		}
	}
	if _u.mutation.TournamentCleared() && len(_u.mutation.TournamentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TournamentEntry.tournament"`)
	}
	if _u.mutation.GolferCleared() && len(_u.mutation.GolferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TournamentEntry.golfer"`)
	}
	return nil
}

func (_u *TournamentEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tournamententry.Table, tournamententry.Columns, sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tournamententry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(tournamententry.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(tournamententry.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Cut(); ok {
		_spec.SetField(tournamententry.FieldCut, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(tournamententry.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(tournamententry.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalStrokes(); ok {
		_spec.SetField(tournamententry.FieldTotalStrokes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalStrokes(); ok {
		_spec.AddField(tournamententry.FieldTotalStrokes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Earnings(); ok {
		_spec.SetField(tournamententry.FieldEarnings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEarnings(); ok {
		_spec.AddField(tournamententry.FieldEarnings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tournamententry.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentRound(); ok {
		_spec.SetField(tournamententry.FieldCurrentRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentRound(); ok {
		_spec.AddField(tournamententry.FieldCurrentRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Thru(); ok {
		_spec.SetField(tournamententry.FieldThru, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThru(); ok {
		_spec.AddField(tournamententry.FieldThru, field.TypeInt, value)
	}
	if _u.mutation.TournamentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.TournamentTable,
			Columns: []string{tournamententry.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.TournamentTable,
			Columns: []string{tournamententry.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GolferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.GolferTable,
			Columns: []string{tournamententry.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GolferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.GolferTable,
			Columns: []string{tournamententry.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tournamententry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TournamentEntryUpdateOne is the builder for updating a single TournamentEntry entity.
type TournamentEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TournamentEntryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TournamentEntryUpdateOne) SetUpdatedAt(v time.Time) *TournamentEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *TournamentEntryUpdateOne) SetPosition(v int) *TournamentEntryUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillablePosition(v *int) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *TournamentEntryUpdateOne) AddPosition(v int) *TournamentEntryUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetCut sets the "cut" field.
func (_u *TournamentEntryUpdateOne) SetCut(v bool) *TournamentEntryUpdateOne {
	_u.mutation.SetCut(v)
	return _u
}

// SetNillableCut sets the "cut" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillableCut(v *bool) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetCut(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *TournamentEntryUpdateOne) SetScore(v int) *TournamentEntryUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillableScore(v *int) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *TournamentEntryUpdateOne) AddScore(v int) *TournamentEntryUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetTotalStrokes sets the "total_strokes" field.
func (_u *TournamentEntryUpdateOne) SetTotalStrokes(v int) *TournamentEntryUpdateOne {
	_u.mutation.ResetTotalStrokes()
	_u.mutation.SetTotalStrokes(v)
	return _u
}

// SetNillableTotalStrokes sets the "total_strokes" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillableTotalStrokes(v *int) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetTotalStrokes(*v)
	}
	return _u
}

// AddTotalStrokes adds value to the "total_strokes" field.
func (_u *TournamentEntryUpdateOne) AddTotalStrokes(v int) *TournamentEntryUpdateOne {
	_u.mutation.AddTotalStrokes(v)
	return _u
}

// SetEarnings sets the "earnings" field.
func (_u *TournamentEntryUpdateOne) SetEarnings(v int) *TournamentEntryUpdateOne {
	_u.mutation.ResetEarnings()
	_u.mutation.SetEarnings(v)
	return _u
}

// SetNillableEarnings sets the "earnings" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillableEarnings(v *int) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetEarnings(*v)
	}
	return _u
}

// AddEarnings adds value to the "earnings" field.
func (_u *TournamentEntryUpdateOne) AddEarnings(v int) *TournamentEntryUpdateOne {
	_u.mutation.AddEarnings(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TournamentEntryUpdateOne) SetStatus(v tournamententry.Status) *TournamentEntryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillableStatus(v *tournamententry.Status) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentRound sets the "current_round" field.
func (_u *TournamentEntryUpdateOne) SetCurrentRound(v int) *TournamentEntryUpdateOne {
	_u.mutation.ResetCurrentRound()
	_u.mutation.SetCurrentRound(v)
	return _u
}

// SetNillableCurrentRound sets the "current_round" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillableCurrentRound(v *int) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetCurrentRound(*v)
	}
	return _u
}

// AddCurrentRound adds value to the "current_round" field.
func (_u *TournamentEntryUpdateOne) AddCurrentRound(v int) *TournamentEntryUpdateOne {
	_u.mutation.AddCurrentRound(v)
	return _u
}

// SetThru sets the "thru" field.
func (_u *TournamentEntryUpdateOne) SetThru(v int) *TournamentEntryUpdateOne {
	_u.mutation.ResetThru()
	_u.mutation.SetThru(v)
	return _u
}

// SetNillableThru sets the "thru" field if the given value is not nil.
func (_u *TournamentEntryUpdateOne) SetNillableThru(v *int) *TournamentEntryUpdateOne {
	if v != nil {
		_u.SetThru(*v)
	}
	return _u
}

// AddThru adds value to the "thru" field.
func (_u *TournamentEntryUpdateOne) AddThru(v int) *TournamentEntryUpdateOne {
	_u.mutation.AddThru(v)
	return _u
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_u *TournamentEntryUpdateOne) SetTournamentID(id uuid.UUID) *TournamentEntryUpdateOne {
	_u.mutation.SetTournamentID(id)
	return _u
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_u *TournamentEntryUpdateOne) SetTournament(v *Tournament) *TournamentEntryUpdateOne {
	return _u.SetTournamentID(v.ID)
}

// SetGolferID sets the "golfer" edge to the Golfer entity by ID.
func (_u *TournamentEntryUpdateOne) SetGolferID(id uuid.UUID) *TournamentEntryUpdateOne {
	_u.mutation.SetGolferID(id)
	return _u
}

// SetGolfer sets the "golfer" edge to the Golfer entity.
func (_u *TournamentEntryUpdateOne) SetGolfer(v *Golfer) *TournamentEntryUpdateOne {
	return _u.SetGolferID(v.ID)
}

// Mutation returns the TournamentEntryMutation object of the builder.
func (_u *TournamentEntryUpdateOne) Mutation() *TournamentEntryMutation {
	return _u.mutation
}

// ClearTournament clears the "tournament" edge to the Tournament entity.
func (_u *TournamentEntryUpdateOne) ClearTournament() *TournamentEntryUpdateOne {
	_u.mutation.ClearTournament()
	return _u
}

// ClearGolfer clears the "golfer" edge to the Golfer entity.
func (_u *TournamentEntryUpdateOne) ClearGolfer() *TournamentEntryUpdateOne {
	_u.mutation.ClearGolfer()
	return _u
}

// Where appends a list predicates to the TournamentEntryUpdate builder.
func (_u *TournamentEntryUpdateOne) Where(ps ...predicate.TournamentEntry) *TournamentEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TournamentEntryUpdateOne) Select(field string, fields ...string) *TournamentEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TournamentEntry entity.
func (_u *TournamentEntryUpdateOne) Save(ctx context.Context) (*TournamentEntry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TournamentEntryUpdateOne) SaveX(ctx context.Context) *TournamentEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TournamentEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TournamentEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TournamentEntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tournamententry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TournamentEntryUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := tournamententry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TournamentEntry.status": %w`, err)}
		}
	}
	if _u.mutation.TournamentCleared() && len(_u.mutation.TournamentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TournamentEntry.tournament"`)
	}
	if _u.mutation.GolferCleared() && len(_u.mutation.GolferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TournamentEntry.golfer"`)
	}
	return nil
}

func (_u *TournamentEntryUpdateOne) sqlSave(ctx context.Context) (_node *TournamentEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tournamententry.Table, tournamententry.Columns, sqlgraph.NewFieldSpec(tournamententry.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TournamentEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tournamententry.FieldID)
		for _, f := range fields {
			if !tournamententry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tournamententry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tournamententry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(tournamententry.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(tournamententry.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Cut(); ok {
		_spec.SetField(tournamententry.FieldCut, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(tournamententry.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(tournamententry.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalStrokes(); ok {
		_spec.SetField(tournamententry.FieldTotalStrokes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalStrokes(); ok {
		_spec.AddField(tournamententry.FieldTotalStrokes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Earnings(); ok {
		_spec.SetField(tournamententry.FieldEarnings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEarnings(); ok {
		_spec.AddField(tournamententry.FieldEarnings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tournamententry.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentRound(); ok {
		_spec.SetField(tournamententry.FieldCurrentRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentRound(); ok {
		_spec.AddField(tournamententry.FieldCurrentRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Thru(); ok {
		_spec.SetField(tournamententry.FieldThru, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThru(); ok {
		_spec.AddField(tournamententry.FieldThru, field.TypeInt, value)
	}
	if _u.mutation.TournamentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.TournamentTable,
			Columns: []string{tournamententry.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.TournamentTable,
			Columns: []string{tournamententry.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GolferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.GolferTable,
			Columns: []string{tournamententry.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GolferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamententry.GolferTable,
			Columns: []string{tournamententry.GolferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(golfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TournamentEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tournamententry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
