// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/golfer"
	"github.com/rj-davidson/greenrats/ent/tournament"
	"github.com/rj-davidson/greenrats/ent/tournamententry"
)

// TournamentEntry is the model entity for the TournamentEntry schema.
type TournamentEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Leaderboard position (parsed from 'T5' -> 5, 0 = not determined)
	Position int `json:"position,omitempty"`
	// True if golfer missed the cut
	Cut bool `json:"cut,omitempty"`
	// Score relative to par (negative is under par)
	Score int `json:"score,omitempty"`
	// Total strokes taken
	TotalStrokes int `json:"total_strokes,omitempty"`
	// Prize money in dollars
	Earnings int `json:"earnings,omitempty"`
	// Golfer's status in the tournament
	Status tournamententry.Status `json:"status,omitempty"`
	// Current round (1-4)
	CurrentRound int `json:"current_round,omitempty"`
	// Holes completed in current round
	Thru int `json:"thru,omitempty"`
	// Field entry status (confirmed, alternate, withdrawn, pending)
	EntryStatus tournamententry.EntryStatus `json:"entry_status,omitempty"`
	// Qualification category (e.g., 'winner', 'exemption', 'sponsor')
	Qualifier *string `json:"qualifier,omitempty"`
	// Official World Golf Ranking at time of field entry
	OwgrAtEntry *int `json:"owgr_at_entry,omitempty"`
	// True if golfer is playing as an amateur
	IsAmateur bool `json:"is_amateur,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TournamentEntryQuery when eager-loading is set.
	Edges              TournamentEntryEdges `json:"edges"`
	golfer_entries     *uuid.UUID
	tournament_entries *uuid.UUID
	selectValues       sql.SelectValues
}

// TournamentEntryEdges holds the relations/edges for other nodes in the graph.
type TournamentEntryEdges struct {
	// Tournament holds the value of the tournament edge.
	Tournament *Tournament `json:"tournament,omitempty"`
	// Golfer holds the value of the golfer edge.
	Golfer *Golfer `json:"golfer,omitempty"`
	// Rounds holds the value of the rounds edge.
	Rounds []*Round `json:"rounds,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TournamentOrErr returns the Tournament value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TournamentEntryEdges) TournamentOrErr() (*Tournament, error) {
	if e.Tournament != nil {
		return e.Tournament, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tournament.Label}
	}
	return nil, &NotLoadedError{edge: "tournament"}
}

// GolferOrErr returns the Golfer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TournamentEntryEdges) GolferOrErr() (*Golfer, error) {
	if e.Golfer != nil {
		return e.Golfer, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: golfer.Label}
	}
	return nil, &NotLoadedError{edge: "golfer"}
}

// RoundsOrErr returns the Rounds value or an error if the edge
// was not loaded in eager-loading.
func (e TournamentEntryEdges) RoundsOrErr() ([]*Round, error) {
	if e.loadedTypes[2] {
		return e.Rounds, nil
	}
	return nil, &NotLoadedError{edge: "rounds"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TournamentEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tournamententry.FieldCut, tournamententry.FieldIsAmateur:
			values[i] = new(sql.NullBool)
		case tournamententry.FieldPosition, tournamententry.FieldScore, tournamententry.FieldTotalStrokes, tournamententry.FieldEarnings, tournamententry.FieldCurrentRound, tournamententry.FieldThru, tournamententry.FieldOwgrAtEntry:
			values[i] = new(sql.NullInt64)
		case tournamententry.FieldStatus, tournamententry.FieldEntryStatus, tournamententry.FieldQualifier:
			values[i] = new(sql.NullString)
		case tournamententry.FieldCreatedAt, tournamententry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case tournamententry.FieldID:
			values[i] = new(uuid.UUID)
		case tournamententry.ForeignKeys[0]: // golfer_entries
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case tournamententry.ForeignKeys[1]: // tournament_entries
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TournamentEntry fields.
func (_m *TournamentEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tournamententry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tournamententry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tournamententry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tournamententry.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case tournamententry.FieldCut:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field cut", values[i])
			} else if value.Valid {
				_m.Cut = value.Bool
			}
		case tournamententry.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = int(value.Int64)
			}
		case tournamententry.FieldTotalStrokes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_strokes", values[i])
			} else if value.Valid {
				_m.TotalStrokes = int(value.Int64)
			}
		case tournamententry.FieldEarnings:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field earnings", values[i])
			} else if value.Valid {
				_m.Earnings = int(value.Int64)
			}
		case tournamententry.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = tournamententry.Status(value.String)
			}
		case tournamententry.FieldCurrentRound:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_round", values[i])
			} else if value.Valid {
				_m.CurrentRound = int(value.Int64)
			}
		case tournamententry.FieldThru:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field thru", values[i])
			} else if value.Valid {
				_m.Thru = int(value.Int64)
			}
		case tournamententry.FieldEntryStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_status", values[i])
			} else if value.Valid {
				_m.EntryStatus = tournamententry.EntryStatus(value.String)
			}
		case tournamententry.FieldQualifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qualifier", values[i])
			} else if value.Valid {
				_m.Qualifier = new(string)
				*_m.Qualifier = value.String
			}
		case tournamententry.FieldOwgrAtEntry:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owgr_at_entry", values[i])
			} else if value.Valid {
				_m.OwgrAtEntry = new(int)
				*_m.OwgrAtEntry = int(value.Int64)
			}
		case tournamententry.FieldIsAmateur:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_amateur", values[i])
			} else if value.Valid {
				_m.IsAmateur = value.Bool
			}
		case tournamententry.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field golfer_entries", values[i])
			} else if value.Valid {
				_m.golfer_entries = new(uuid.UUID)
				*_m.golfer_entries = *value.S.(*uuid.UUID)
			}
		case tournamententry.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field tournament_entries", values[i])
			} else if value.Valid {
				_m.tournament_entries = new(uuid.UUID)
				*_m.tournament_entries = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TournamentEntry.
// This includes values selected through modifiers, order, etc.
func (_m *TournamentEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTournament queries the "tournament" edge of the TournamentEntry entity.
func (_m *TournamentEntry) QueryTournament() *TournamentQuery {
	return NewTournamentEntryClient(_m.config).QueryTournament(_m)
}

// QueryGolfer queries the "golfer" edge of the TournamentEntry entity.
func (_m *TournamentEntry) QueryGolfer() *GolferQuery {
	return NewTournamentEntryClient(_m.config).QueryGolfer(_m)
}

// QueryRounds queries the "rounds" edge of the TournamentEntry entity.
func (_m *TournamentEntry) QueryRounds() *RoundQuery {
	return NewTournamentEntryClient(_m.config).QueryRounds(_m)
}

// Update returns a builder for updating this TournamentEntry.
// Note that you need to call TournamentEntry.Unwrap() before calling this method if this TournamentEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TournamentEntry) Update() *TournamentEntryUpdateOne {
	return NewTournamentEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TournamentEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TournamentEntry) Unwrap() *TournamentEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TournamentEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TournamentEntry) String() string {
	var builder strings.Builder
	builder.WriteString("TournamentEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("cut=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cut))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("total_strokes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalStrokes))
	builder.WriteString(", ")
	builder.WriteString("earnings=")
	builder.WriteString(fmt.Sprintf("%v", _m.Earnings))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("current_round=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentRound))
	builder.WriteString(", ")
	builder.WriteString("thru=")
	builder.WriteString(fmt.Sprintf("%v", _m.Thru))
	builder.WriteString(", ")
	builder.WriteString("entry_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryStatus))
	builder.WriteString(", ")
	if v := _m.Qualifier; v != nil {
		builder.WriteString("qualifier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OwgrAtEntry; v != nil {
		builder.WriteString("owgr_at_entry=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_amateur=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAmateur))
	builder.WriteByte(')')
	return builder.String()
}

// TournamentEntries is a parsable slice of TournamentEntry.
type TournamentEntries []*TournamentEntry
