// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/course"
	"github.com/rj-davidson/greenrats/ent/tournament"
	"github.com/rj-davidson/greenrats/ent/tournamentcourse"
)

// TournamentCourseCreate is the builder for creating a TournamentCourse entity.
type TournamentCourseCreate struct {
	config
	mutation *TournamentCourseMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TournamentCourseCreate) SetCreatedAt(v time.Time) *TournamentCourseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TournamentCourseCreate) SetNillableCreatedAt(v *time.Time) *TournamentCourseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TournamentCourseCreate) SetUpdatedAt(v time.Time) *TournamentCourseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TournamentCourseCreate) SetNillableUpdatedAt(v *time.Time) *TournamentCourseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRounds sets the "rounds" field.
func (_c *TournamentCourseCreate) SetRounds(v []int) *TournamentCourseCreate {
	_c.mutation.SetRounds(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TournamentCourseCreate) SetID(v uuid.UUID) *TournamentCourseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TournamentCourseCreate) SetNillableID(v *uuid.UUID) *TournamentCourseCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_c *TournamentCourseCreate) SetTournamentID(id uuid.UUID) *TournamentCourseCreate {
	_c.mutation.SetTournamentID(id)
	return _c
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_c *TournamentCourseCreate) SetTournament(v *Tournament) *TournamentCourseCreate {
	return _c.SetTournamentID(v.ID)
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (_c *TournamentCourseCreate) SetCourseID(id uuid.UUID) *TournamentCourseCreate {
	_c.mutation.SetCourseID(id)
	return _c
}

// SetCourse sets the "course" edge to the Course entity.
func (_c *TournamentCourseCreate) SetCourse(v *Course) *TournamentCourseCreate {
	return _c.SetCourseID(v.ID)
}

// Mutation returns the TournamentCourseMutation object of the builder.
func (_c *TournamentCourseCreate) Mutation() *TournamentCourseMutation {
	return _c.mutation
}

// Save creates the TournamentCourse in the database.
func (_c *TournamentCourseCreate) Save(ctx context.Context) (*TournamentCourse, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TournamentCourseCreate) SaveX(ctx context.Context) *TournamentCourse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TournamentCourseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TournamentCourseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TournamentCourseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tournamentcourse.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tournamentcourse.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tournamentcourse.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TournamentCourseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TournamentCourse.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TournamentCourse.updated_at"`)}
	}
	if len(_c.mutation.TournamentIDs()) == 0 {
		return &ValidationError{Name: "tournament", err: errors.New(`ent: missing required edge "TournamentCourse.tournament"`)}
	}
	if len(_c.mutation.CourseIDs()) == 0 {
		return &ValidationError{Name: "course", err: errors.New(`ent: missing required edge "TournamentCourse.course"`)}
	}
	return nil
}

func (_c *TournamentCourseCreate) sqlSave(ctx context.Context) (*TournamentCourse, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TournamentCourseCreate) createSpec() (*TournamentCourse, *sqlgraph.CreateSpec) {
	var (
		_node = &TournamentCourse{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tournamentcourse.Table, sqlgraph.NewFieldSpec(tournamentcourse.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tournamentcourse.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tournamentcourse.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Rounds(); ok {
		_spec.SetField(tournamentcourse.FieldRounds, field.TypeJSON, value)
		_node.Rounds = value
	}
	if nodes := _c.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamentcourse.TournamentTable,
			Columns: []string{tournamentcourse.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tournament_tournament_courses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournamentcourse.CourseTable,
			Columns: []string{tournamentcourse.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.course_tournament_courses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TournamentCourseCreateBulk is the builder for creating many TournamentCourse entities in bulk.
type TournamentCourseCreateBulk struct {
	config
	err      error
	builders []*TournamentCourseCreate
}

// Save creates the TournamentCourse entities in the database.
func (_c *TournamentCourseCreateBulk) Save(ctx context.Context) ([]*TournamentCourse, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TournamentCourse, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TournamentCourseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TournamentCourseCreateBulk) SaveX(ctx context.Context) []*TournamentCourse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TournamentCourseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TournamentCourseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
