// Code generated by ent, DO NOT EDIT.

package coursehole

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
)

const (
	// Label holds the string label denoting the coursehole type in the database.
	Label = "course_hole"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHoleNumber holds the string denoting the hole_number field in the database.
	FieldHoleNumber = "hole_number"
	// FieldPar holds the string denoting the par field in the database.
	FieldPar = "par"
	// FieldYardage holds the string denoting the yardage field in the database.
	FieldYardage = "yardage"
	// EdgeCourse holds the string denoting the course edge name in mutations.
	EdgeCourse = "course"
	// Table holds the table name of the coursehole in the database.
	Table = "course_holes"
	// CourseTable is the table that holds the course relation/edge.
	CourseTable = "course_holes"
	// CourseInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CourseInverseTable = "courses"
	// CourseColumn is the table column denoting the course relation/edge.
	CourseColumn = "course_holes"
)

// Columns holds all SQL columns for coursehole fields.
var Columns = []string{
	FieldID,
	FieldHoleNumber,
	FieldPar,
	FieldYardage,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "course_holes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"course_holes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// HoleNumberValidator is a validator for the "hole_number" field. It is called by the builders before save.
	HoleNumberValidator func(int) error
	// ParValidator is a validator for the "par" field. It is called by the builders before save.
	ParValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the CourseHole queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHoleNumber orders the results by the hole_number field.
func ByHoleNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoleNumber, opts...).ToFunc()
}

// ByPar orders the results by the par field.
func ByPar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPar, opts...).ToFunc()
}

// ByYardage orders the results by the yardage field.
func ByYardage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYardage, opts...).ToFunc()
}

// ByCourseField orders the results by course field.
func ByCourseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCourseStep(), sql.OrderByField(field, opts...))
	}
}
func newCourseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CourseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
	)
}
