// Code generated by ent, DO NOT EDIT.

package coursehole

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLTE(FieldID, id))
}

// HoleNumber applies equality check predicate on the "hole_number" field. It's identical to HoleNumberEQ.
func HoleNumber(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldHoleNumber, v))
}

// Par applies equality check predicate on the "par" field. It's identical to ParEQ.
func Par(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldPar, v))
}

// Yardage applies equality check predicate on the "yardage" field. It's identical to YardageEQ.
func Yardage(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldYardage, v))
}

// HoleNumberEQ applies the EQ predicate on the "hole_number" field.
func HoleNumberEQ(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldHoleNumber, v))
}

// HoleNumberNEQ applies the NEQ predicate on the "hole_number" field.
func HoleNumberNEQ(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNEQ(FieldHoleNumber, v))
}

// HoleNumberIn applies the In predicate on the "hole_number" field.
func HoleNumberIn(vs ...int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldIn(FieldHoleNumber, vs...))
}

// HoleNumberNotIn applies the NotIn predicate on the "hole_number" field.
func HoleNumberNotIn(vs ...int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNotIn(FieldHoleNumber, vs...))
}

// HoleNumberGT applies the GT predicate on the "hole_number" field.
func HoleNumberGT(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGT(FieldHoleNumber, v))
}

// HoleNumberGTE applies the GTE predicate on the "hole_number" field.
func HoleNumberGTE(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGTE(FieldHoleNumber, v))
}

// HoleNumberLT applies the LT predicate on the "hole_number" field.
func HoleNumberLT(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLT(FieldHoleNumber, v))
}

// HoleNumberLTE applies the LTE predicate on the "hole_number" field.
func HoleNumberLTE(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLTE(FieldHoleNumber, v))
}

// ParEQ applies the EQ predicate on the "par" field.
func ParEQ(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldPar, v))
}

// ParNEQ applies the NEQ predicate on the "par" field.
func ParNEQ(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNEQ(FieldPar, v))
}

// ParIn applies the In predicate on the "par" field.
func ParIn(vs ...int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldIn(FieldPar, vs...))
}

// ParNotIn applies the NotIn predicate on the "par" field.
func ParNotIn(vs ...int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNotIn(FieldPar, vs...))
}

// ParGT applies the GT predicate on the "par" field.
func ParGT(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGT(FieldPar, v))
}

// ParGTE applies the GTE predicate on the "par" field.
func ParGTE(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGTE(FieldPar, v))
}

// ParLT applies the LT predicate on the "par" field.
func ParLT(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLT(FieldPar, v))
}

// ParLTE applies the LTE predicate on the "par" field.
func ParLTE(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLTE(FieldPar, v))
}

// YardageEQ applies the EQ predicate on the "yardage" field.
func YardageEQ(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldEQ(FieldYardage, v))
}

// YardageNEQ applies the NEQ predicate on the "yardage" field.
func YardageNEQ(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNEQ(FieldYardage, v))
}

// YardageIn applies the In predicate on the "yardage" field.
func YardageIn(vs ...int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldIn(FieldYardage, vs...))
}

// YardageNotIn applies the NotIn predicate on the "yardage" field.
func YardageNotIn(vs ...int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNotIn(FieldYardage, vs...))
}

// YardageGT applies the GT predicate on the "yardage" field.
func YardageGT(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGT(FieldYardage, v))
}

// YardageGTE applies the GTE predicate on the "yardage" field.
func YardageGTE(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldGTE(FieldYardage, v))
}

// YardageLT applies the LT predicate on the "yardage" field.
func YardageLT(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLT(FieldYardage, v))
}

// YardageLTE applies the LTE predicate on the "yardage" field.
func YardageLTE(v int) predicate.CourseHole {
	return predicate.CourseHole(sql.FieldLTE(FieldYardage, v))
}

// YardageIsNil applies the IsNil predicate on the "yardage" field.
func YardageIsNil() predicate.CourseHole {
	return predicate.CourseHole(sql.FieldIsNull(FieldYardage))
}

// YardageNotNil applies the NotNil predicate on the "yardage" field.
func YardageNotNil() predicate.CourseHole {
	return predicate.CourseHole(sql.FieldNotNull(FieldYardage))
}

// HasCourse applies the HasEdge predicate on the "course" edge.
func HasCourse() predicate.CourseHole {
	return predicate.CourseHole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCourseWith applies the HasEdge predicate on the "course" edge with a given conditions (other predicates).
func HasCourseWith(preds ...predicate.Course) predicate.CourseHole {
	return predicate.CourseHole(func(s *sql.Selector) {
		step := newCourseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CourseHole) predicate.CourseHole {
	return predicate.CourseHole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CourseHole) predicate.CourseHole {
	return predicate.CourseHole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CourseHole) predicate.CourseHole {
	return predicate.CourseHole(sql.NotPredicates(p))
}
