// Code generated by ent, DO NOT EDIT.

package tournament

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
)

const (
	// Label holds the string label denoting the tournament type in the database.
	Label = "tournament"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldBdlID holds the string denoting the bdl_id field in the database.
	FieldBdlID = "bdl_id"
	// FieldPgaTourID holds the string denoting the pga_tour_id field in the database.
	FieldPgaTourID = "pga_tour_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldSeasonYear holds the string denoting the season_year field in the database.
	FieldSeasonYear = "season_year"
	// FieldCourse holds the string denoting the course field in the database.
	FieldCourse = "course"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldPickWindowOpensAt holds the string denoting the pick_window_opens_at field in the database.
	FieldPickWindowOpensAt = "pick_window_opens_at"
	// FieldPickWindowClosesAt holds the string denoting the pick_window_closes_at field in the database.
	FieldPickWindowClosesAt = "pick_window_closes_at"
	// FieldPurse holds the string denoting the purse field in the database.
	FieldPurse = "purse"
	// EdgePicks holds the string denoting the picks edge name in mutations.
	EdgePicks = "picks"
	// EdgeFieldEntries holds the string denoting the field_entries edge name in mutations.
	EdgeFieldEntries = "field_entries"
	// EdgePlacements holds the string denoting the placements edge name in mutations.
	EdgePlacements = "placements"
	// EdgeRounds holds the string denoting the rounds edge name in mutations.
	EdgeRounds = "rounds"
	// EdgeEmailReminders holds the string denoting the email_reminders edge name in mutations.
	EdgeEmailReminders = "email_reminders"
	// EdgeTournamentCourses holds the string denoting the tournament_courses edge name in mutations.
	EdgeTournamentCourses = "tournament_courses"
	// EdgeChampion holds the string denoting the champion edge name in mutations.
	EdgeChampion = "champion"
	// EdgeSeason holds the string denoting the season edge name in mutations.
	EdgeSeason = "season"
	// EdgeCourseRef holds the string denoting the course_ref edge name in mutations.
	EdgeCourseRef = "course_ref"
	// Table holds the table name of the tournament in the database.
	Table = "tournaments"
	// PicksTable is the table that holds the picks relation/edge.
	PicksTable = "picks"
	// PicksInverseTable is the table name for the Pick entity.
	// It exists in this package in order to avoid circular dependency with the "pick" package.
	PicksInverseTable = "picks"
	// PicksColumn is the table column denoting the picks relation/edge.
	PicksColumn = "tournament_picks"
	// FieldEntriesTable is the table that holds the field_entries relation/edge.
	FieldEntriesTable = "field_entries"
	// FieldEntriesInverseTable is the table name for the FieldEntry entity.
	// It exists in this package in order to avoid circular dependency with the "fieldentry" package.
	FieldEntriesInverseTable = "field_entries"
	// FieldEntriesColumn is the table column denoting the field_entries relation/edge.
	FieldEntriesColumn = "tournament_field_entries"
	// PlacementsTable is the table that holds the placements relation/edge.
	PlacementsTable = "placements"
	// PlacementsInverseTable is the table name for the Placement entity.
	// It exists in this package in order to avoid circular dependency with the "placement" package.
	PlacementsInverseTable = "placements"
	// PlacementsColumn is the table column denoting the placements relation/edge.
	PlacementsColumn = "tournament_placements"
	// RoundsTable is the table that holds the rounds relation/edge.
	RoundsTable = "rounds"
	// RoundsInverseTable is the table name for the Round entity.
	// It exists in this package in order to avoid circular dependency with the "round" package.
	RoundsInverseTable = "rounds"
	// RoundsColumn is the table column denoting the rounds relation/edge.
	RoundsColumn = "tournament_rounds"
	// EmailRemindersTable is the table that holds the email_reminders relation/edge.
	EmailRemindersTable = "email_reminders"
	// EmailRemindersInverseTable is the table name for the EmailReminder entity.
	// It exists in this package in order to avoid circular dependency with the "emailreminder" package.
	EmailRemindersInverseTable = "email_reminders"
	// EmailRemindersColumn is the table column denoting the email_reminders relation/edge.
	EmailRemindersColumn = "tournament_email_reminders"
	// TournamentCoursesTable is the table that holds the tournament_courses relation/edge.
	TournamentCoursesTable = "tournament_courses"
	// TournamentCoursesInverseTable is the table name for the TournamentCourse entity.
	// It exists in this package in order to avoid circular dependency with the "tournamentcourse" package.
	TournamentCoursesInverseTable = "tournament_courses"
	// TournamentCoursesColumn is the table column denoting the tournament_courses relation/edge.
	TournamentCoursesColumn = "tournament_tournament_courses"
	// ChampionTable is the table that holds the champion relation/edge.
	ChampionTable = "tournaments"
	// ChampionInverseTable is the table name for the Golfer entity.
	// It exists in this package in order to avoid circular dependency with the "golfer" package.
	ChampionInverseTable = "golfers"
	// ChampionColumn is the table column denoting the champion relation/edge.
	ChampionColumn = "tournament_champion"
	// SeasonTable is the table that holds the season relation/edge.
	SeasonTable = "tournaments"
	// SeasonInverseTable is the table name for the Season entity.
	// It exists in this package in order to avoid circular dependency with the "season" package.
	SeasonInverseTable = "seasons"
	// SeasonColumn is the table column denoting the season relation/edge.
	SeasonColumn = "season_tournaments"
	// CourseRefTable is the table that holds the course_ref relation/edge.
	CourseRefTable = "tournaments"
	// CourseRefInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CourseRefInverseTable = "courses"
	// CourseRefColumn is the table column denoting the course_ref relation/edge.
	CourseRefColumn = "course_tournaments"
)

// Columns holds all SQL columns for tournament fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldBdlID,
	FieldPgaTourID,
	FieldName,
	FieldStartDate,
	FieldEndDate,
	FieldSeasonYear,
	FieldCourse,
	FieldCity,
	FieldState,
	FieldCountry,
	FieldTimezone,
	FieldPickWindowOpensAt,
	FieldPickWindowClosesAt,
	FieldPurse,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tournaments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"course_tournaments",
	"season_tournaments",
	"tournament_champion",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Tournament queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBdlID orders the results by the bdl_id field.
func ByBdlID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBdlID, opts...).ToFunc()
}

// ByPgaTourID orders the results by the pga_tour_id field.
func ByPgaTourID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPgaTourID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// BySeasonYear orders the results by the season_year field.
func BySeasonYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeasonYear, opts...).ToFunc()
}

// ByCourse orders the results by the course field.
func ByCourse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCourse, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByPickWindowOpensAt orders the results by the pick_window_opens_at field.
func ByPickWindowOpensAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPickWindowOpensAt, opts...).ToFunc()
}

// ByPickWindowClosesAt orders the results by the pick_window_closes_at field.
func ByPickWindowClosesAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPickWindowClosesAt, opts...).ToFunc()
}

// ByPurse orders the results by the purse field.
func ByPurse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurse, opts...).ToFunc()
}

// ByPicksCount orders the results by picks count.
func ByPicksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPicksStep(), opts...)
	}
}

// ByPicks orders the results by picks terms.
func ByPicks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPicksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFieldEntriesCount orders the results by field_entries count.
func ByFieldEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFieldEntriesStep(), opts...)
	}
}

// ByFieldEntries orders the results by field_entries terms.
func ByFieldEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFieldEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPlacementsCount orders the results by placements count.
func ByPlacementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlacementsStep(), opts...)
	}
}

// ByPlacements orders the results by placements terms.
func ByPlacements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlacementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRoundsCount orders the results by rounds count.
func ByRoundsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoundsStep(), opts...)
	}
}

// ByRounds orders the results by rounds terms.
func ByRounds(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoundsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEmailRemindersCount orders the results by email_reminders count.
func ByEmailRemindersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEmailRemindersStep(), opts...)
	}
}

// ByEmailReminders orders the results by email_reminders terms.
func ByEmailReminders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmailRemindersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTournamentCoursesCount orders the results by tournament_courses count.
func ByTournamentCoursesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTournamentCoursesStep(), opts...)
	}
}

// ByTournamentCourses orders the results by tournament_courses terms.
func ByTournamentCourses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTournamentCoursesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChampionField orders the results by champion field.
func ByChampionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChampionStep(), sql.OrderByField(field, opts...))
	}
}

// BySeasonField orders the results by season field.
func BySeasonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeasonStep(), sql.OrderByField(field, opts...))
	}
}

// ByCourseRefField orders the results by course_ref field.
func ByCourseRefField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCourseRefStep(), sql.OrderByField(field, opts...))
	}
}
func newPicksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PicksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PicksTable, PicksColumn),
	)
}
func newFieldEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FieldEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FieldEntriesTable, FieldEntriesColumn),
	)
}
func newPlacementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlacementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlacementsTable, PlacementsColumn),
	)
}
func newRoundsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoundsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RoundsTable, RoundsColumn),
	)
}
func newEmailRemindersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmailRemindersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EmailRemindersTable, EmailRemindersColumn),
	)
}
func newTournamentCoursesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TournamentCoursesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TournamentCoursesTable, TournamentCoursesColumn),
	)
}
func newChampionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChampionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ChampionTable, ChampionColumn),
	)
}
func newSeasonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeasonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SeasonTable, SeasonColumn),
	)
}
func newCourseRefStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CourseRefInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CourseRefTable, CourseRefColumn),
	)
}
