// Code generated by ent, DO NOT EDIT.

package tournament

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
)

const (
	// Label holds the string label denoting the tournament type in the database.
	Label = "tournament"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldScratchgolfID holds the string denoting the scratchgolf_id field in the database.
	FieldScratchgolfID = "scratchgolf_id"
	// FieldBdlID holds the string denoting the bdl_id field in the database.
	FieldBdlID = "bdl_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSeasonYear holds the string denoting the season_year field in the database.
	FieldSeasonYear = "season_year"
	// FieldCourse holds the string denoting the course field in the database.
	FieldCourse = "course"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldPurse holds the string denoting the purse field in the database.
	FieldPurse = "purse"
	// EdgePicks holds the string denoting the picks edge name in mutations.
	EdgePicks = "picks"
	// EdgeEntries holds the string denoting the entries edge name in mutations.
	EdgeEntries = "entries"
	// EdgeEmailReminders holds the string denoting the email_reminders edge name in mutations.
	EdgeEmailReminders = "email_reminders"
	// Table holds the table name of the tournament in the database.
	Table = "tournaments"
	// PicksTable is the table that holds the picks relation/edge.
	PicksTable = "picks"
	// PicksInverseTable is the table name for the Pick entity.
	// It exists in this package in order to avoid circular dependency with the "pick" package.
	PicksInverseTable = "picks"
	// PicksColumn is the table column denoting the picks relation/edge.
	PicksColumn = "tournament_picks"
	// EntriesTable is the table that holds the entries relation/edge.
	EntriesTable = "tournament_entries"
	// EntriesInverseTable is the table name for the TournamentEntry entity.
	// It exists in this package in order to avoid circular dependency with the "tournamententry" package.
	EntriesInverseTable = "tournament_entries"
	// EntriesColumn is the table column denoting the entries relation/edge.
	EntriesColumn = "tournament_entries"
	// EmailRemindersTable is the table that holds the email_reminders relation/edge.
	EmailRemindersTable = "email_reminders"
	// EmailRemindersInverseTable is the table name for the EmailReminder entity.
	// It exists in this package in order to avoid circular dependency with the "emailreminder" package.
	EmailRemindersInverseTable = "email_reminders"
	// EmailRemindersColumn is the table column denoting the email_reminders relation/edge.
	EmailRemindersColumn = "tournament_email_reminders"
)

// Columns holds all SQL columns for tournament fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldScratchgolfID,
	FieldBdlID,
	FieldName,
	FieldStartDate,
	FieldEndDate,
	FieldStatus,
	FieldSeasonYear,
	FieldCourse,
	FieldLocation,
	FieldPurse,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUpcoming is the default value of the Status enum.
const DefaultStatus = StatusUpcoming

// Status values.
const (
	StatusUpcoming  Status = "upcoming"
	StatusActive    Status = "active"
	StatusCompleted Status = "completed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusUpcoming, StatusActive, StatusCompleted:
		return nil
	default:
		return fmt.Errorf("tournament: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Tournament queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScratchgolfID orders the results by the scratchgolf_id field.
func ByScratchgolfID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScratchgolfID, opts...).ToFunc()
}

// ByBdlID orders the results by the bdl_id field.
func ByBdlID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBdlID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySeasonYear orders the results by the season_year field.
func BySeasonYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeasonYear, opts...).ToFunc()
}

// ByCourse orders the results by the course field.
func ByCourse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCourse, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByPurse orders the results by the purse field.
func ByPurse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurse, opts...).ToFunc()
}

// ByPicksCount orders the results by picks count.
func ByPicksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPicksStep(), opts...)
	}
}

// ByPicks orders the results by picks terms.
func ByPicks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPicksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEntriesCount orders the results by entries count.
func ByEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEntriesStep(), opts...)
	}
}

// ByEntries orders the results by entries terms.
func ByEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEmailRemindersCount orders the results by email_reminders count.
func ByEmailRemindersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEmailRemindersStep(), opts...)
	}
}

// ByEmailReminders orders the results by email_reminders terms.
func ByEmailReminders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmailRemindersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPicksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PicksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PicksTable, PicksColumn),
	)
}
func newEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
	)
}
func newEmailRemindersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmailRemindersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EmailRemindersTable, EmailRemindersColumn),
	)
}
