// Code generated by ent, DO NOT EDIT.

package tournament

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScratchgolfID applies equality check predicate on the "scratchgolf_id" field. It's identical to ScratchgolfIDEQ.
func ScratchgolfID(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldScratchgolfID, v))
}

// BdlID applies equality check predicate on the "bdl_id" field. It's identical to BdlIDEQ.
func BdlID(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldBdlID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldName, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldEndDate, v))
}

// SeasonYear applies equality check predicate on the "season_year" field. It's identical to SeasonYearEQ.
func SeasonYear(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldSeasonYear, v))
}

// Course applies equality check predicate on the "course" field. It's identical to CourseEQ.
func Course(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCourse, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldLocation, v))
}

// Purse applies equality check predicate on the "purse" field. It's identical to PurseEQ.
func Purse(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldPurse, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldUpdatedAt, v))
}

// ScratchgolfIDEQ applies the EQ predicate on the "scratchgolf_id" field.
func ScratchgolfIDEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldScratchgolfID, v))
}

// ScratchgolfIDNEQ applies the NEQ predicate on the "scratchgolf_id" field.
func ScratchgolfIDNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldScratchgolfID, v))
}

// ScratchgolfIDIn applies the In predicate on the "scratchgolf_id" field.
func ScratchgolfIDIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldScratchgolfID, vs...))
}

// ScratchgolfIDNotIn applies the NotIn predicate on the "scratchgolf_id" field.
func ScratchgolfIDNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldScratchgolfID, vs...))
}

// ScratchgolfIDGT applies the GT predicate on the "scratchgolf_id" field.
func ScratchgolfIDGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldScratchgolfID, v))
}

// ScratchgolfIDGTE applies the GTE predicate on the "scratchgolf_id" field.
func ScratchgolfIDGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldScratchgolfID, v))
}

// ScratchgolfIDLT applies the LT predicate on the "scratchgolf_id" field.
func ScratchgolfIDLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldScratchgolfID, v))
}

// ScratchgolfIDLTE applies the LTE predicate on the "scratchgolf_id" field.
func ScratchgolfIDLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldScratchgolfID, v))
}

// ScratchgolfIDContains applies the Contains predicate on the "scratchgolf_id" field.
func ScratchgolfIDContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldScratchgolfID, v))
}

// ScratchgolfIDHasPrefix applies the HasPrefix predicate on the "scratchgolf_id" field.
func ScratchgolfIDHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldScratchgolfID, v))
}

// ScratchgolfIDHasSuffix applies the HasSuffix predicate on the "scratchgolf_id" field.
func ScratchgolfIDHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldScratchgolfID, v))
}

// ScratchgolfIDIsNil applies the IsNil predicate on the "scratchgolf_id" field.
func ScratchgolfIDIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldScratchgolfID))
}

// ScratchgolfIDNotNil applies the NotNil predicate on the "scratchgolf_id" field.
func ScratchgolfIDNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldScratchgolfID))
}

// ScratchgolfIDEqualFold applies the EqualFold predicate on the "scratchgolf_id" field.
func ScratchgolfIDEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldScratchgolfID, v))
}

// ScratchgolfIDContainsFold applies the ContainsFold predicate on the "scratchgolf_id" field.
func ScratchgolfIDContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldScratchgolfID, v))
}

// BdlIDEQ applies the EQ predicate on the "bdl_id" field.
func BdlIDEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldBdlID, v))
}

// BdlIDNEQ applies the NEQ predicate on the "bdl_id" field.
func BdlIDNEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldBdlID, v))
}

// BdlIDIn applies the In predicate on the "bdl_id" field.
func BdlIDIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldBdlID, vs...))
}

// BdlIDNotIn applies the NotIn predicate on the "bdl_id" field.
func BdlIDNotIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldBdlID, vs...))
}

// BdlIDGT applies the GT predicate on the "bdl_id" field.
func BdlIDGT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldBdlID, v))
}

// BdlIDGTE applies the GTE predicate on the "bdl_id" field.
func BdlIDGTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldBdlID, v))
}

// BdlIDLT applies the LT predicate on the "bdl_id" field.
func BdlIDLT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldBdlID, v))
}

// BdlIDLTE applies the LTE predicate on the "bdl_id" field.
func BdlIDLTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldBdlID, v))
}

// BdlIDIsNil applies the IsNil predicate on the "bdl_id" field.
func BdlIDIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldBdlID))
}

// BdlIDNotNil applies the NotNil predicate on the "bdl_id" field.
func BdlIDNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldBdlID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldName, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldEndDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldStatus, vs...))
}

// SeasonYearEQ applies the EQ predicate on the "season_year" field.
func SeasonYearEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldSeasonYear, v))
}

// SeasonYearNEQ applies the NEQ predicate on the "season_year" field.
func SeasonYearNEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldSeasonYear, v))
}

// SeasonYearIn applies the In predicate on the "season_year" field.
func SeasonYearIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldSeasonYear, vs...))
}

// SeasonYearNotIn applies the NotIn predicate on the "season_year" field.
func SeasonYearNotIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldSeasonYear, vs...))
}

// SeasonYearGT applies the GT predicate on the "season_year" field.
func SeasonYearGT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldSeasonYear, v))
}

// SeasonYearGTE applies the GTE predicate on the "season_year" field.
func SeasonYearGTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldSeasonYear, v))
}

// SeasonYearLT applies the LT predicate on the "season_year" field.
func SeasonYearLT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldSeasonYear, v))
}

// SeasonYearLTE applies the LTE predicate on the "season_year" field.
func SeasonYearLTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldSeasonYear, v))
}

// CourseEQ applies the EQ predicate on the "course" field.
func CourseEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCourse, v))
}

// CourseNEQ applies the NEQ predicate on the "course" field.
func CourseNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldCourse, v))
}

// CourseIn applies the In predicate on the "course" field.
func CourseIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldCourse, vs...))
}

// CourseNotIn applies the NotIn predicate on the "course" field.
func CourseNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldCourse, vs...))
}

// CourseGT applies the GT predicate on the "course" field.
func CourseGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldCourse, v))
}

// CourseGTE applies the GTE predicate on the "course" field.
func CourseGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldCourse, v))
}

// CourseLT applies the LT predicate on the "course" field.
func CourseLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldCourse, v))
}

// CourseLTE applies the LTE predicate on the "course" field.
func CourseLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldCourse, v))
}

// CourseContains applies the Contains predicate on the "course" field.
func CourseContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldCourse, v))
}

// CourseHasPrefix applies the HasPrefix predicate on the "course" field.
func CourseHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldCourse, v))
}

// CourseHasSuffix applies the HasSuffix predicate on the "course" field.
func CourseHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldCourse, v))
}

// CourseIsNil applies the IsNil predicate on the "course" field.
func CourseIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldCourse))
}

// CourseNotNil applies the NotNil predicate on the "course" field.
func CourseNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldCourse))
}

// CourseEqualFold applies the EqualFold predicate on the "course" field.
func CourseEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldCourse, v))
}

// CourseContainsFold applies the ContainsFold predicate on the "course" field.
func CourseContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldCourse, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationIsNil applies the IsNil predicate on the "location" field.
func LocationIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldLocation))
}

// LocationNotNil applies the NotNil predicate on the "location" field.
func LocationNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldLocation))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldLocation, v))
}

// PurseEQ applies the EQ predicate on the "purse" field.
func PurseEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldPurse, v))
}

// PurseNEQ applies the NEQ predicate on the "purse" field.
func PurseNEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldPurse, v))
}

// PurseIn applies the In predicate on the "purse" field.
func PurseIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldPurse, vs...))
}

// PurseNotIn applies the NotIn predicate on the "purse" field.
func PurseNotIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldPurse, vs...))
}

// PurseGT applies the GT predicate on the "purse" field.
func PurseGT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldPurse, v))
}

// PurseGTE applies the GTE predicate on the "purse" field.
func PurseGTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldPurse, v))
}

// PurseLT applies the LT predicate on the "purse" field.
func PurseLT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldPurse, v))
}

// PurseLTE applies the LTE predicate on the "purse" field.
func PurseLTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldPurse, v))
}

// PurseIsNil applies the IsNil predicate on the "purse" field.
func PurseIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldPurse))
}

// PurseNotNil applies the NotNil predicate on the "purse" field.
func PurseNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldPurse))
}

// HasPicks applies the HasEdge predicate on the "picks" edge.
func HasPicks() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PicksTable, PicksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPicksWith applies the HasEdge predicate on the "picks" edge with a given conditions (other predicates).
func HasPicksWith(preds ...predicate.Pick) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newPicksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGolfers applies the HasEdge predicate on the "golfers" edge.
func HasGolfers() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GolfersTable, GolfersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGolfersWith applies the HasEdge predicate on the "golfers" edge with a given conditions (other predicates).
func HasGolfersWith(preds ...predicate.Golfer) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newGolfersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntries applies the HasEdge predicate on the "entries" edge.
func HasEntries() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntriesWith applies the HasEdge predicate on the "entries" edge with a given conditions (other predicates).
func HasEntriesWith(preds ...predicate.TournamentEntry) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tournament) predicate.Tournament {
	return predicate.Tournament(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tournament) predicate.Tournament {
	return predicate.Tournament(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tournament) predicate.Tournament {
	return predicate.Tournament(sql.NotPredicates(p))
}
