// Code generated by ent, DO NOT EDIT.

package tournamententry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/rj-davidson/greenrats/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldPosition, v))
}

// Cut applies equality check predicate on the "cut" field. It's identical to CutEQ.
func Cut(v bool) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldCut, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldScore, v))
}

// TotalStrokes applies equality check predicate on the "total_strokes" field. It's identical to TotalStrokesEQ.
func TotalStrokes(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldTotalStrokes, v))
}

// Earnings applies equality check predicate on the "earnings" field. It's identical to EarningsEQ.
func Earnings(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldEarnings, v))
}

// CurrentRound applies equality check predicate on the "current_round" field. It's identical to CurrentRoundEQ.
func CurrentRound(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldCurrentRound, v))
}

// Thru applies equality check predicate on the "thru" field. It's identical to ThruEQ.
func Thru(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldThru, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldPosition, v))
}

// CutEQ applies the EQ predicate on the "cut" field.
func CutEQ(v bool) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldCut, v))
}

// CutNEQ applies the NEQ predicate on the "cut" field.
func CutNEQ(v bool) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldCut, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldScore, v))
}

// TotalStrokesEQ applies the EQ predicate on the "total_strokes" field.
func TotalStrokesEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldTotalStrokes, v))
}

// TotalStrokesNEQ applies the NEQ predicate on the "total_strokes" field.
func TotalStrokesNEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldTotalStrokes, v))
}

// TotalStrokesIn applies the In predicate on the "total_strokes" field.
func TotalStrokesIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldTotalStrokes, vs...))
}

// TotalStrokesNotIn applies the NotIn predicate on the "total_strokes" field.
func TotalStrokesNotIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldTotalStrokes, vs...))
}

// TotalStrokesGT applies the GT predicate on the "total_strokes" field.
func TotalStrokesGT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldTotalStrokes, v))
}

// TotalStrokesGTE applies the GTE predicate on the "total_strokes" field.
func TotalStrokesGTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldTotalStrokes, v))
}

// TotalStrokesLT applies the LT predicate on the "total_strokes" field.
func TotalStrokesLT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldTotalStrokes, v))
}

// TotalStrokesLTE applies the LTE predicate on the "total_strokes" field.
func TotalStrokesLTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldTotalStrokes, v))
}

// EarningsEQ applies the EQ predicate on the "earnings" field.
func EarningsEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldEarnings, v))
}

// EarningsNEQ applies the NEQ predicate on the "earnings" field.
func EarningsNEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldEarnings, v))
}

// EarningsIn applies the In predicate on the "earnings" field.
func EarningsIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldEarnings, vs...))
}

// EarningsNotIn applies the NotIn predicate on the "earnings" field.
func EarningsNotIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldEarnings, vs...))
}

// EarningsGT applies the GT predicate on the "earnings" field.
func EarningsGT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldEarnings, v))
}

// EarningsGTE applies the GTE predicate on the "earnings" field.
func EarningsGTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldEarnings, v))
}

// EarningsLT applies the LT predicate on the "earnings" field.
func EarningsLT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldEarnings, v))
}

// EarningsLTE applies the LTE predicate on the "earnings" field.
func EarningsLTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldEarnings, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldStatus, vs...))
}

// CurrentRoundEQ applies the EQ predicate on the "current_round" field.
func CurrentRoundEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldCurrentRound, v))
}

// CurrentRoundNEQ applies the NEQ predicate on the "current_round" field.
func CurrentRoundNEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldCurrentRound, v))
}

// CurrentRoundIn applies the In predicate on the "current_round" field.
func CurrentRoundIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldCurrentRound, vs...))
}

// CurrentRoundNotIn applies the NotIn predicate on the "current_round" field.
func CurrentRoundNotIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldCurrentRound, vs...))
}

// CurrentRoundGT applies the GT predicate on the "current_round" field.
func CurrentRoundGT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldCurrentRound, v))
}

// CurrentRoundGTE applies the GTE predicate on the "current_round" field.
func CurrentRoundGTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldCurrentRound, v))
}

// CurrentRoundLT applies the LT predicate on the "current_round" field.
func CurrentRoundLT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldCurrentRound, v))
}

// CurrentRoundLTE applies the LTE predicate on the "current_round" field.
func CurrentRoundLTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldCurrentRound, v))
}

// ThruEQ applies the EQ predicate on the "thru" field.
func ThruEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldEQ(FieldThru, v))
}

// ThruNEQ applies the NEQ predicate on the "thru" field.
func ThruNEQ(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNEQ(FieldThru, v))
}

// ThruIn applies the In predicate on the "thru" field.
func ThruIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldIn(FieldThru, vs...))
}

// ThruNotIn applies the NotIn predicate on the "thru" field.
func ThruNotIn(vs ...int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldNotIn(FieldThru, vs...))
}

// ThruGT applies the GT predicate on the "thru" field.
func ThruGT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGT(FieldThru, v))
}

// ThruGTE applies the GTE predicate on the "thru" field.
func ThruGTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldGTE(FieldThru, v))
}

// ThruLT applies the LT predicate on the "thru" field.
func ThruLT(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLT(FieldThru, v))
}

// ThruLTE applies the LTE predicate on the "thru" field.
func ThruLTE(v int) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.FieldLTE(FieldThru, v))
}

// HasTournament applies the HasEdge predicate on the "tournament" edge.
func HasTournament() predicate.TournamentEntry {
	return predicate.TournamentEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TournamentTable, TournamentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTournamentWith applies the HasEdge predicate on the "tournament" edge with a given conditions (other predicates).
func HasTournamentWith(preds ...predicate.Tournament) predicate.TournamentEntry {
	return predicate.TournamentEntry(func(s *sql.Selector) {
		step := newTournamentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGolfer applies the HasEdge predicate on the "golfer" edge.
func HasGolfer() predicate.TournamentEntry {
	return predicate.TournamentEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GolferTable, GolferColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGolferWith applies the HasEdge predicate on the "golfer" edge with a given conditions (other predicates).
func HasGolferWith(preds ...predicate.Golfer) predicate.TournamentEntry {
	return predicate.TournamentEntry(func(s *sql.Selector) {
		step := newGolferStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TournamentEntry) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TournamentEntry) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TournamentEntry) predicate.TournamentEntry {
	return predicate.TournamentEntry(sql.NotPredicates(p))
}
