// Code generated by ent, DO NOT EDIT.

package emailreminder

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
)

const (
	// Label holds the string label denoting the emailreminder type in the database.
	Label = "email_reminder"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReminderType holds the string denoting the reminder_type field in the database.
	FieldReminderType = "reminder_type"
	// FieldSentAt holds the string denoting the sent_at field in the database.
	FieldSentAt = "sent_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeTournament holds the string denoting the tournament edge name in mutations.
	EdgeTournament = "tournament"
	// EdgeLeague holds the string denoting the league edge name in mutations.
	EdgeLeague = "league"
	// Table holds the table name of the emailreminder in the database.
	Table = "email_reminders"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "email_reminders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_email_reminders"
	// TournamentTable is the table that holds the tournament relation/edge.
	TournamentTable = "email_reminders"
	// TournamentInverseTable is the table name for the Tournament entity.
	// It exists in this package in order to avoid circular dependency with the "tournament" package.
	TournamentInverseTable = "tournaments"
	// TournamentColumn is the table column denoting the tournament relation/edge.
	TournamentColumn = "tournament_email_reminders"
	// LeagueTable is the table that holds the league relation/edge.
	LeagueTable = "email_reminders"
	// LeagueInverseTable is the table name for the League entity.
	// It exists in this package in order to avoid circular dependency with the "league" package.
	LeagueInverseTable = "leagues"
	// LeagueColumn is the table column denoting the league relation/edge.
	LeagueColumn = "league_email_reminders"
)

// Columns holds all SQL columns for emailreminder fields.
var Columns = []string{
	FieldID,
	FieldReminderType,
	FieldSentAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "email_reminders"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"league_email_reminders",
	"tournament_email_reminders",
	"user_email_reminders",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSentAt holds the default value on creation for the "sent_at" field.
	DefaultSentAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ReminderType defines the type for the "reminder_type" enum field.
type ReminderType string

// ReminderType values.
const (
	ReminderTypePickReminder      ReminderType = "pick_reminder"
	ReminderTypeTournamentResults ReminderType = "tournament_results"
)

func (rt ReminderType) String() string {
	return string(rt)
}

// ReminderTypeValidator is a validator for the "reminder_type" field enum values. It is called by the builders before save.
func ReminderTypeValidator(rt ReminderType) error {
	switch rt {
	case ReminderTypePickReminder, ReminderTypeTournamentResults:
		return nil
	default:
		return fmt.Errorf("emailreminder: invalid enum value for reminder_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the EmailReminder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByReminderType orders the results by the reminder_type field.
func ByReminderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReminderType, opts...).ToFunc()
}

// BySentAt orders the results by the sent_at field.
func BySentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByTournamentField orders the results by tournament field.
func ByTournamentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTournamentStep(), sql.OrderByField(field, opts...))
	}
}

// ByLeagueField orders the results by league field.
func ByLeagueField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLeagueStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newTournamentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TournamentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TournamentTable, TournamentColumn),
	)
}
func newLeagueStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LeagueInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LeagueTable, LeagueColumn),
	)
}
